images/Utils.ps1

Some of the image versions have changed in the meanwhile. This patch updates them.

Updates image versions

---

README.md

@PatrickLang @jsturtevant
Does this look right? Just went through the process myself.

Adding documentation for how to build e2e tests

---

job-templates/kubernetes_release_staging.json

I'm adding these to the staging file first. If they pass a few times, I can merge them into the main one.

Updating to Docker 18.09.2 and enabling OpenSSH

---

job-templates/kubernetes_release.json
job-templates/kubernetes_release_staging.json

Disable automatic updates for windows nodes to prevent nodes rebooting during tests.

Disable automatic updates

---

images/Utils.ps1

Recently, some changes were made to the liveness code, and the image version was bumped.
Fixes #42

images: Updates liveness version to 1.1

---

job-templates/kubernetes_release_staging.json

Clusters spawned from this template continue to have problems, particularly with the CNI. Reverting the state to the previously known working state.

Set staging job to previous known good state.

---

extensions/agent_preprovision_extension/v1/node_setup.ps1
extensions/master_extension/v1/supported-orchestrators.json
extensions/master_extension/v1/template-link.json
extensions/master_extension/v1/template.json
extensions/master_extension/v1/win-e2e-master-extension.sh
job-templates/kubernetes_release_staging.json

Move all extensions to this repo & have templates use them from here.

Update extensions & job templates

---

extensions/agent_preprovision_extension/v1/node_setup.ps1

disable Windows Defender on Windows nodes - workaround for #75148

Disable Windows Defender

---

job-templates/kubernetes_master.json

Adding a new template file for master job.
In relation with https://github.com/kubernetes/test-infra/pull/12598

Add new job template file for master job

---

job-templates/kubernetes_release_staging.json

testing latest released azure cni

---

job-templates/kubernetes_release_1_15.json

At the moment this file is identical to the template used for master, however in future the will probably divagate so it's best to make them separate now.

Add job template for 1.15 branch

---

job-templates/kubernetes_release_staging.json

This windows patch includes a fix that solves DNS errors
eg: https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-staging-windows/1132858835212439555

Adding windows patch KB4497934

---

job-templates/kubernetes_master.json

Updating mater job with:
1. windows nodes patch KB4497934 
2. Azure CNI v1.0.22

Updating master job 

---

job-templates/kubernetes_master.json
job-templates/kubernetes_release_1_15.json
job-templates/kubernetes_release_staging.json

Reason: https://github.com/kubernetes/kubernetes/issues/78628

Disable KubeletPodResources feature.

---

job-templates/kubernetes_release_1_15.json

Upgrading 1.15 job:
- azure cni to 1.0.22
- install KB patch in order to fix DNS errors

Upgrade 1.15 job

---

job-templates/kubernetes_release_staging.json

This is a workaround  for https://github.com/kubernetes-sigs/windows-testing/issues/73

Adding --runtime-config flag

---

images/httpd/Dockerfile
images/httpd/index.html

A few changes are required in order for the E2E tests to properly use this image.

images: Amends the httpd image

---

images/Utils.ps1

The image version used in E2E tests has been changed.

images: Updates redis image version

---

job-templates/kubernetes_release_staging.json

In order to test solution for: https://github.com/kubernetes-sigs/windows-testing/issues/87

Adding 1min sleep in master extension

---

extensions/master_extension/v1/win-e2e-master-extension.sh

In order to fix 
https://github.com/kubernetes-sigs/windows-testing/issues/87

Adding 60sec sleep before while in master extension

---

job-templates/kubernetes_release_staging.json

Issue https://github.com/kubernetes-sigs/windows-testing/issues/87 was fixed

Use master extension from official repo

---

job-templates/kubernetes_master.json
job-templates/kubernetes_release_1_15.json

Update includes newer docker versions and Windows images.

Update job templates for 1.15 k8s and master jobs.

---

job-templates/kubernetes_release_staging.json

- Add gmsa-coredns extension to master
- Add gmsa-member extension to windowspool1
- Add "windowsgmsa" pool with gmsa-dc extension

Add GMSA extensions

---

gce/load-test.sh
gce/loadtest-prepull.yaml

Add GCE load test scripts

---

job-templates/kubernetes_master.json

Updating some old values in kubernetes_master template

updating old values in kubernetes_master template

---

job-templates/kubernetes_release_1_14.json
job-templates/kubernetes_release_1_18.json

Creating job template for 1.18 release and also copying 1.14 template to a better named file.

Release 1.18 job template

---

gce/hack-run-e2e.sh
gce/run-e2e.sh

https://github.com/kubernetes-sigs/windows-testing/pull/145#issuecomment-599642648

switched run-e2e.sh and hack-run-e2e.sh to fix the gce windows e2e tests

---

OWNERS
job-templates/kubernetes_storage.json

Reverts kubernetes-sigs/windows-testing#161

Revert "chore: set the count of master to 3 in windows cluster"

---

job-templates/kubernetes_containerd.json

Update kubernetes_containerd.json job template to remove nested kubernetesConfig section which is invalid.

fix: fix kubernetes_containerd.json template

---

README.md

Updates documentation for using kubetest locally.
cc: @chewong @marosset

Fix documentation for kubetest

---

README.md

docs: update kubetest docs in README.md

---

job-templates/kubernetes_2004_containerd.json
job-templates/kubernetes_2004_containerd_hyperv.json

Add templates for testing containerd against WS 20.04

Add 2004 containerd templates

---

extensions/gmsa-coredns/v1/update-coredns.sh
extensions/master_extension/v1/win-e2e-master-extension.sh
scripts/win-ci-logs-collector.sh

Fixes test failure in https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-2004/1288631402773876737.
Fixes partially https://github.com/kubernetes/kubernetes/issues/93590.
Master extension logs:
```
Tue, 04 Aug 2020 23:48:11 +0000: start master extension
Tue, 04 Aug 2020 23:48:11 +0000: wait for agent nodes
real	2m45.180s
user	0m1.685s
sys	0m0.417s
```

fix: wait for agent nodes to become available before running master extension

---

extensions/hyperv-mutating-webhook/v1/configure-hyperv-webhook.sh
extensions/hyperv-mutating-webhook/v1/template.json
job-templates/kubernetes_2004_containerd_hyperv.json
scripts/win-ci-logs-collector.sh

- Addressing some PR feedback on previous PR
- Updating references to point to kubernetes-sigs/master
- Updating config to to install mutating webhook for 2004-containerd-hyperv aks-engine config

2004 hyperv testing config updates

---

job-templates/kubernetes_containerd_master.json
job-templates/kubernetes_containerd_master_serial.json

chore: use containerd nightly build for master branch jobs

---

job-templates/kubernetes_csi_proxy.json

upgrade to csi-proxy v0.2.0

---

job-templates/kubernetes_2004_containerd_hyperv.json
job-templates/kubernetes_containerd_hyperv.json

Update containerd package 0.0.11-1

Update containerd package 0.0.11-1

---

job-templates/kubernetes_csi_proxy.json

original 2 core VM is too small
/assign @ZeroMagic

use Standard_D4s_v3 for windows testing

---

job-templates/kubernetes_2004_containerd_hyperv.json
job-templates/kubernetes_containerd_hyperv.json

updating containerd package to v0.0.13 which has fixes for cpu-limit for hyper-v isolated containers

updating containerd package to v0.0.13 

---

job-templates/kubernetes_containerd_csi_proxy.json

Adding a containerd + csi-proxy aks-engine template in order to set up PROW jobs to test this containerd + csi-proxy

Adding containerd + csi-proxy aks-engine template

---

extensions/master_extension/v1/win-e2e-master-extension.sh

fixes https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-1-18-windows/1316416954558320640

fix: increase agent node timeout from 500 to 900 seconds

---

job-templates/kubernetes_containerd_csi_proxy.json

fixing kubernetes_contianerd_csi-proxy job template

fixing kubernetes_contianerd_csi-proxy job template

---

job-templates/kubernetes_2004_containerd_hyperv.json
job-templates/kubernetes_containerd_hyperv.json

/assign @jsturtevant @marosset 
fixes
- https://testgrid.k8s.io/provider-azure-windows#aks-engine-azure-windows-master-containerd-hyperv
- https://testgrid.k8s.io/provider-azure-windows#aks-engine-azure-windows-master-containerd-hyperv-serial-slow
- https://testgrid.k8s.io/provider-azure-windows#aks-engine-azure-windows-2004-master-containerd-hyperv
- https://testgrid.k8s.io/provider-azure-windows#aks-engine-azure-windows-master-2004-containerd-hyperv-serial-slow

fix: explicitly disable useManagedIdentity for hyperv API model

---

gce/prepull-1.14.yaml
gce/prepull-1.15.yaml
gce/prepull-1.16.yaml
gce/prepull-1.17.yaml
gce/prepull-1.18.yaml
gce/prepull.yaml
helpers/hyper-v-mutating-webhook/deployment.yaml
images/BuildImageManifestLists.ps1
images/BuildImages.ps1
images/MirrorUpstreamK8sImgs.ps1
images/PullImages.ps1
images/agnhost/Dockerfile
images/busybox/Dockerfile
images/cassandra/Dockerfile
images/dnsutils/Dockerfile
images/echoserver/Dockerfile
images/hazelcast-kubernetes/Dockerfile
images/hostexec/Dockerfile
images/iperf/Dockerfile
images/java/Dockerfile
images/jessie-dnsutils/Dockerfile
images/kitten/Dockerfile
images/nautilus/Dockerfile
images/net/Dockerfile
images/netexec/Dockerfile
images/nfs-server/Dockerfile
images/nginx/Dockerfile
images/redis/Dockerfile
images/rethinkdb/Dockerfile

/assign @jsturtevant @adelina-t @marosset @claudiubelu

images: replace e2eteam with k8sprow.azurecr.io/kubernetes-e2e-test-images

---

job-templates/kubernetes_release_1_20.json
job-templates/kubernetes_release_1_20_serial.json

Adding k8s 1.20 release configs

---

extensions/master_extension/v1/win-e2e-master-extension.sh

fix: increase wait_for_agent_nodes function timeout to 30m

---

job-templates/kubernetes_1903_1_18.json

Removing RunAsUserName feature gate from test configs targeting 1.18

---

job-templates/kubernetes_2004_containerd.json
job-templates/kubernetes_containerd_1_19.json
job-templates/kubernetes_containerd_1_19_serial.json
job-templates/kubernetes_containerd_hyperv.json
job-templates/kubernetes_containerd_master.json
job-templates/kubernetes_containerd_master_serial.json
job-templates/kubernetes_release_1_19.json
job-templates/kubernetes_release_1_19_serial.json
job-templates/kubernetes_release_1_20.json
job-templates/kubernetes_release_1_20_serial.json
job-templates/kubernetes_release_staging.json
job-templates/kubernetes_release_staging_serial.json

Important update for Windows CNI: https://github.com/Azure/azure-container-networking/pull/755
cc: @abelhu
/assign @chewong @marosset

Update azure cni version to 1.2.2 and containerd to v1.4.3

---

job-templates/kubernetes_containerd_1_19.json
job-templates/kubernetes_containerd_1_19_serial.json
job-templates/kubernetes_containerd_hyperv.json
job-templates/kubernetes_containerd_master.json
job-templates/kubernetes_containerd_master_serial.json
job-templates/kubernetes_release_1_17.json
job-templates/kubernetes_release_1_17_serial.json
job-templates/kubernetes_release_1_18.json
job-templates/kubernetes_release_1_18_serial.json
job-templates/kubernetes_release_1_19.json
job-templates/kubernetes_release_1_19_serial.json
job-templates/kubernetes_release_1_20.json
job-templates/kubernetes_release_1_20_serial.json
job-templates/kubernetes_release_staging.json
job-templates/kubernetes_release_staging_serial.json

This should help with some flakes that are related to pulling the latest versions of components.
/assign @chewong @marosset

Update vhds to latest versions built

---

gce/prepull-1.21.yaml

Signed-off-by: Jeremy Edwards <1312331+jeremyje@users.noreply.github.com>
/sig windows
/priority important-soon

Add prepull from k8s.gcr.io based images.

---

images/image-repo-list-master

This e2eprivate registry has support for 20H2.

Make image-repo-list-master use e2eprivate gcAuthenticatedRegistry.

---

README.md

The presubmits were renamed during testgrid dashboard update
/assign @marosset @chewong

Update README with correct test name

---

job-templates/kubernetes_containerd_1_20.json
job-templates/kubernetes_containerd_1_20_serial.json
job-templates/kubernetes_containerd_1_21.json
job-templates/kubernetes_containerd_1_21_serial.json
job-templates/kubernetes_release_1_20_serial.json
job-templates/kubernetes_release_1_21.json
job-templates/kubernetes_release_1_21_serial.json

test: add additional 1.20 and 1.21 aks-engine API models

---

job-templates/kubernetes_2004_containerd.json
job-templates/kubernetes_containerd_1_19.json
job-templates/kubernetes_containerd_1_19_serial.json
job-templates/kubernetes_containerd_1_20.json
job-templates/kubernetes_containerd_1_20_serial.json
job-templates/kubernetes_containerd_1_21.json
job-templates/kubernetes_containerd_1_21_serial.json
job-templates/kubernetes_containerd_1_5.json
job-templates/kubernetes_containerd_hyperv.json
job-templates/kubernetes_containerd_master-hostprocess.json
job-templates/kubernetes_containerd_master.json
job-templates/kubernetes_containerd_master_serial.json
job-templates/kubernetes_release_1_18.json
job-templates/kubernetes_release_1_19.json
job-templates/kubernetes_release_1_19_serial.json
job-templates/kubernetes_release_1_20.json
job-templates/kubernetes_release_1_21.json
job-templates/kubernetes_release_1_21_serial.json
job-templates/kubernetes_release_staging.json
job-templates/kubernetes_release_staging_serial.json

Updating to latest azure cni version
/sig windows
/assign @chewong

Update azure cni to latest release 1.4.4

---

job-templates/kubernetes_containerd_master-hostprocess.json

https://github.com/microsoft/hcsshim/pull/962 merged so we can use the nightly package instead of custom package
/sig windows
/assign @chewong

Use nightly containerd and hcsshim

---

job-templates/kubernetes_containerd_nightly.json
job-templates/kubernetes_release_staging.json
job-templates/kubernetes_release_staging_serial.json

enabling accelerated networking for staging cluster definitions

---

job-templates/kubernetes_2004_containerd.json
job-templates/kubernetes_20h2_master.json
job-templates/kubernetes_containerd_1_20.json
job-templates/kubernetes_containerd_1_20_serial.json
job-templates/kubernetes_containerd_1_21.json
job-templates/kubernetes_containerd_1_21_serial.json
job-templates/kubernetes_containerd_1_22.json
job-templates/kubernetes_containerd_1_22_serial.json
job-templates/kubernetes_containerd_csi_proxy.json
job-templates/kubernetes_containerd_master.json
job-templates/kubernetes_containerd_master_csi_enabled.json
job-templates/kubernetes_containerd_master_serial.json

using the latest containerd version
/cc @marosset @abelhu

update ctrd version to 1.5.8

---

job-templates/kubernetes_containerd_1_23.json
job-templates/kubernetes_containerd_1_23_serial.json

1.23 branch was cut.  Adding the template for the release team monitoring.

Add Containerd 1.23 templates

---

job-templates/kubernetes_20h2_master.json
job-templates/kubernetes_containerd_1_20.json
job-templates/kubernetes_containerd_1_20_serial.json
job-templates/kubernetes_containerd_1_21.json
job-templates/kubernetes_containerd_1_21_serial.json
job-templates/kubernetes_containerd_1_22.json
job-templates/kubernetes_containerd_1_22_serial.json
job-templates/kubernetes_containerd_1_23.json
job-templates/kubernetes_containerd_1_23_serial.json
job-templates/kubernetes_containerd_csi_proxy.json
job-templates/kubernetes_containerd_hyperv.json
job-templates/kubernetes_containerd_master.json
job-templates/kubernetes_containerd_master_csi_enabled.json
job-templates/kubernetes_containerd_master_serial.json
job-templates/kubernetes_containerd_nightly.json
job-templates/kubernetes_in_tree_containerd.json

Updating containerd to 1.6.0-rc.1 and OS patches

---

job-templates/kubernetes_containerd_1_23.json
job-templates/kubernetes_containerd_1_23_serial.json
job-templates/kubernetes_containerd_master.json
job-templates/kubernetes_containerd_master_csi_enabled.json
job-templates/kubernetes_containerd_master_serial.json

Updating templates to use containerd 1.6 for 1.23 and master branches

---

OWNERS

This will allow the mentioned username to approve PRs on the repository.

Adds claudiubelu to OWNERS

---

scripts/ci-k8s-unit-test.sh
scripts/enable_ssh_windows.ps1
scripts/k8s_unit_windows.ps1
scripts/prepare_env_windows.ps1

Part of implementing prow jobs for Windows unit tests. These scripts take care of VM creation, package installation & test running + log collection.

Unit test scripts windows

---

.github/workflows/capz.yml
capz/run-capz-e2e.sh

Need to create a workflow file initially for it to be triggered on #328 on my fork

create capz workflow with linter enabled

---

capz/templates/windows-base.yaml

This should have been included in #332 

Api server requires the setting HPA feature gate 

---

job-templates/kubernetes_containerd_1_21.json
job-templates/kubernetes_containerd_1_21_serial.json
job-templates/kubernetes_containerd_1_22.json
job-templates/kubernetes_containerd_1_22_serial.json
job-templates/kubernetes_containerd_1_23.json
job-templates/kubernetes_containerd_1_23_serial.json
job-templates/kubernetes_containerd_1_24.json
job-templates/kubernetes_containerd_1_24_csi_enabled.json
job-templates/kubernetes_release_1_21.json
job-templates/kubernetes_release_1_21_serial.json
job-templates/kubernetes_release_1_22.json
job-templates/kubernetes_release_1_23.json

chore: use Windows VHDs with 7C 2022 patches

---

capz/readme.md
capz/run-capz-e2e.sh

az capi readme and minor updates

---

capz/run-capz-e2e.sh

Default to v0.0.6 of az capi extension

---

gce/hack-run-e2e.sh
gce/run-e2e.sh

See https://github.com/kubernetes/kubernetes/issues/89477, https://github.com/kubernetes/kubernetes/issues/89477#issuecomment-603911496.

Stop using the beta.kubernetes.io/os

---

scripts/k8s_unit_windows.ps1

Currently, the ``k8s.io/kubernetes/cmd/kubeadm/test/cmd`` unit tests are failing because they're expecting the ``KUBEADM_PATH`` env variable to be set.
The unit tests script is now building the kubeadm binary on Windows and setting the aforementioned env variable before running the unit tests.
Note: We have to inject a few version-related variables into k8s.io/component-base/version. By default, these fields are not set or they will be set when git archive is run, and the version-related unit tests would fail otherwise, since it wouldn't match the expected regexes.
Fixes: https://github.com/kubernetes-sigs/windows-testing/issues/343

Builds kubeadm.exe for Windows unit tests

---

capz/readme.md
capz/run-capz-e2e.sh

Also updating default contianerd to 1.6.17
/assign @mboersma @jsturtevant

Updating az capi extension source to v0.1.3 which supports installing KPNG

---

capz/run-capz-e2e.sh

Don't restart kube-proxy ds if configured to run kpng

---

OWNERS

/sig windows
/assign @jayunit100 @claudiubelu @jsturtevant

OWNERS file cleanup

---

capz/templates/gmsa-ci.yaml
capz/templates/gmsa-pr.yaml
capz/templates/windows-base.yaml
capz/templates/windows-ci.yaml
capz/templates/windows-pr.yaml

Allows for jobs to specific node level feature gates in the prow jobs.

Add support for node level features

---

capz/run-capz-e2e.sh

Fixing issue in run_capz-e2e.sh where log cleanup does not happen after calling ci-build-kubernetes.sh

---

capz/run-capz-e2e.sh

Getting more logs to help root-cause https://github.com/kubernetes/kubernetes/issues/118993
/sig windows
/assign @CecileRobertMichon @mboersma

Adding --debug to az capi SIG Windows jobs

---

capz/run-capz-e2e.sh

Stop calling --debug in az capi

---

capz/templates/gmsa-ci.yaml
capz/templates/gmsa-pr.yaml
capz/templates/windows-base.yaml
capz/templates/windows-ci.yaml
capz/templates/windows-pr.yaml

/assign @aravindhp @jsturtevant 
This time I **correctly** verified nodes come online with this feature enabled

Fixing issue where nodeLogQuery feature was not actually enabled

---

capz/run-capz-e2e.sh

Fixing an issue where run-capz-e2e.sh fails if run from capz directory

---

capz/templates/ci/patches/kubeadm-bootstrap-control-plane-ci.yaml
capz/templates/ci/patches/kubeadm-bootstrap-windows-ci.yaml
capz/templates/gmsa-ci.yaml
capz/templates/windows-ci.yaml

/assign @jsturtevant @claudiubelu

Removing --short=true flag from kubectl version because it was removed

---

capz/run-capz-e2e.sh

use e2e.test built from the PR branch for presubmit jobs
/hold
hold until https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4173 is cherry-picked into `release-1.11`
/assign @jsturtevant @CecileRobertMichon

use e2e built from PR branch for presubmits

---

capz/run-capz-e2e.sh

chmod +x e2e.test for presubmit runs

---

capz/run-capz-e2e.sh

always extract kubernetes-test-linux-amd64.tar.gz since it contains ginkgo

---

capz/readme.md
capz/templates/gmsa-ci.yaml
capz/templates/gmsa-pr.yaml
capz/templates/windows-base.yaml
capz/templates/windows-ci.yaml
capz/templates/windows-pr.yaml

Updating capz/readme.md to add more optional env vars and also add required setup after CAPZ switched to using out-of-tree cloud provider images
/assign @jsturtevant @aravindhp

Updating capz/readme.md

---

capz/run-capz-e2e.sh

This is used for the username to SSH into nodes

capz: Export KUBE_SSH_USER

---

capz/templates/shared-image-gallery-ci.yaml
capz/templates/sig/patches/shared-gallery.yaml

Updates Annual Channel image to latest version

Update annual channel image

---

capz/run-capz-e2e.sh

updates to latest cert-manager version

Update cert-manager deploy for hyperv

---

capz/run-capz-e2e.sh

Add flake attempt retry

---

capz/run-capz-e2e.sh

We saw an issue with the AKS region running out of capacity, this is a attemp to retry if it occurs
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows/1796557544848625664
```
ERROR: (AKSCapacityError) Creating a free tier cluster is unavailable at this time in region westeurope. To create a new cluster, we recommend using an alternate region, or create a paid tier cluster. For a list of all the Azure regions, visit https://aka.ms/aks/regions. For more details on this error, visit https://aka.ms/akscapacityerror.
```

Retry creating cluster with new name and region

---

capz/run-capz-e2e.sh

Follow up for https://github.com/kubernetes/test-infra/pull/32976 and https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4978

remove file that was removed in capz

---

capz/run-capz-e2e.sh

Drop west Europe do to re-occurring capacity issues

---

capz/run-capz-e2e.sh

fixes: https://github.com/kubernetes/kubernetes/issues/126321
/assign @ritikaguptams @aravindhp

Skip DynamicResourceAllocation

---

scripts/ci-k8s-unit-test.sh

/sig windows
Federated Id's are the only way to log in with the new sub. This follows changes in capz: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4939

Use federated token to sign-in on new sub

---

capz/readme.md

Quick fix, the az command brought to sync with current az cli offering.

Fixing az command in readme

---

capz/run-capz-e2e.sh

follow up to https://github.com/kubernetes/test-infra/pull/34101

Use latest gallery image

---

capz/run-capz-e2e.sh

All are non-critical changes
(1): Add a "region" env, so that use can pick their preferred region if they want
(2): when re-using the resource group, also reset the location to the value of the RG. 
(3): Delete the role assignment for the added MI, it looks that there will be residues if we do not delete it even after the MI being deleted, and also looks there will be quotas for the number of role assignments, so do the cleaning if possible.
(4): Also make the setting of SKIP-XXX env to be in the same "true/false" format

minor fixes

---

scripts/ci-k8s-unit-test.sh
scripts/k8s_unit_windows.ps1

Skip known failures for windows unit tests

---

scripts/k8s_unit_windows.ps1

Fixes: https://github.com/kubernetes-sigs/windows-testing/issues/503

kubeadm buildflags from ci
