kubernetes-sigs/windows-testing

README.md, images/image-repo-list-ws1803, images/image-repo-list-ws2019
The lists are originally located in github.com/e2e-win/e2e-win-prow-deployment
Move the lists to the official sig-windows testing repository and update
the README.
=> Add test image repo lists

job-templates/kubernetes_release.json
The current config used to test on Azure uses a `Standard_D2_v3` VM with standard storage. This change moves it to [Standard_D2s_v3](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/sizes-general) which allows SSD storage, and increases the disk size so it will get the [P10](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/premium-storage#premium-storage-disk-limits) disk for 500 IOPs.
The latest run [225](https://gubernator.k8s.io/build/kubernetes-jenkins/logs/ci-kubernetes-e2e-win-1-13/225) took 41 minutes to deploy all the VMs, which includes pulling the Windows test images.
In my testing, the same deployment took 37 minutes. It may also decrease the time to run individual test cases since pods may start faster. I can't measure that as easily so I would …
=> Change Windows VM to use a 500 IOPs disk instead of 120

extensions/master_extension/v1/win-e2e-master-extension.sh
The taint "key=value:NoSchedule" might get applied before all the pods in the kube-system are up and running, meaning that they will be stuck in a "Pending" state.
The kube-system pods have the tolerange "node-role.kubernetes.io/master", so setting the taint "node-role.kubernetes.io/master=:NoSchedule" instead would be a good idea.
=> Updates the taint set in the win-e2e-master-extension

images/gb-frontend/Dockerfile
A new php version has been released (7.3), causing it to install into the folder c:\tools\php73, which different from what the rest of the Dockerfile was using. Because of this, the image was no longer able to start.
This commit pins the installed apache-httpd and php versions.
Fixes: #10
=> gb-frontend: Pins apache-httpd and php versions

job-templates/kubernetes_release.json
Force use of Azure CNI 1.0.16 as version 1.0.17 seems less stable.
=> Add custom 1.0.16 Azure CNI URL to template.

job-templates/kubernetes_release.json
I should have double checked those URLs in #14 . They looked right, but the second one was wrong.
Tests:
```
$ curl -o azure-cni.tgz https://acs-mirror.azureedge.net/cni/azure-vnet-cni-linux-amd64-v1.0.16.tgz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 4261k  100 4261k    0     0  4141k      0  0:00:01  0:00:01 --:--:-- 4141k
$ tar tvzf azure-cni.tgz
-rwxr-xr-x root/root   5842912 2019-01-10 22:24 azure-vnet
-rwxr-xr-x root/root   5308960 2019-01-10 22:24 azure-vnet-ipam
-rw-r--r-- root/root       368 2019-01-10 22:24 10-azure.conflist
patrick@planglx1:~/pr14$ curl -o azure-cni.zip https://acs-mirror.azureedge.net/cni/azure-vnet-cni-windows-amd64-v1.0.16.zip
% Total    % Received % Xferd  Average Speed …
```
=> Fixing Azure-CNI 1.0.16 URL

images/BuildImageManifestLists.ps1, images/Utils.ps1, images/image-repo-list
Adds BuildImageManifestLists.ps1 script which builds and tags the images
based on predefined base images.
At the moment, the base images we're building on top of are:
- microsoft/windowsservercore:1803
- mcr.microsoft.com/windows/servercore:ltsc2019
The script also adds suffixes (1803 and 1809 respectively) to the image
versions. Those images can then be pushed to dockerhub.
Finally, the script will create manifest lists for the images, which can
then be pushed to dockerhub.
=> Adds image Manifest lists

README.md
I reorganized the README to
1) Put a link to the latest test results near the top
2) Split the rest of the document into building and running a subset of tests with `e2e.test`, and running a full test pass with `kubetest`
@adelina-t or @bclau - can you review the Azure section? I took the steps from https://github.com/e2e-win/e2e-win-prow-deployment, but updated them using the latest parameters from sig-windows-config.yaml.
=> Improving build & test steps

job-templates/kubernetes_release.json
Clusters cannot be deployed with more than one extension per agent pool.
=> Remove winrm extension and custom cni links

images/resource-consumer/consume-cpu/consume_cpu_windows.go, images/resource-consumer/utils.go
This executable attempts to maintain around a target level of CPU usage.
For that to work, it has to calculate its current usage correctly. The
calculation is based on a syscall that returns the cpu time this process
has used so far. However, the loading of that return value into a struct
was incorrect; by summing each cpu usage value with itself, the estimate
of current cpu usage was doubled. This results in the container using
less than the requested number of millicores.
This commit also makes some variable names more readable and add a
couple comments explaining the purpose of the helper functions. Doing
all calculations in millicores rather than percentages makes the code
more aligned with the input it takes.
Relevant to https://github.com/kubernetes/kubernetes/issues/73489
=> Correct calculation of CPU usage.

job-templates/kubernetes_release.json
Remove installation of hotfix on Windows nodes via windows_patches
extension as new versions of Windows from Azure contain it already.
=> Remove windows_patches extension

job-templates/kubernetes_release_staging.json
The template for the main job ( kubernetes_template.json ) will
have pinned versions for Windows Image, CNI version and Docker version.
The reason behind the change is to protect the main job against
changes in these components that may affect the success of tests.
The staging job ( with template kubernetes_staging_template.json ) will
be used to experiment with new versions for CNI etc.
=> Add separate templates for staging job and main job.

images/busybox/Dockerfile, images/hostexec/Dockerfile
Adds the nc.exe executable to the busybox image, as it is required
by some tests (https://github.com/kubernetes/kubernetes/pull/74290).
Removes nc.exe from the hostexec Dockerfile because the hostexec
image is based on the busybox image, so it will contain the nc.exe.
=> Adds nc.exe to the busybox image

build/build-windows-k8s.sh
Build script is based on:  https://raw.githubusercontent.com/Azure/acs-engine/master/scripts/build-windows-k8s.sh 
and only contains relevant bits for building binaries for upstream jobs.
Also contains NSSM mirror url so that we eliminate the dependency on nssm.cc which has been unstable lately.
=> Add build script for windows binaries

images/gb-frontend/run.ps1, images/gb-redisslave/run.ps1
Containers might start without any initial network connectivity, but
some images require it. The gb-frontend and gb-redisslave images need
to resolve some DNS names in order to work properly.
This commit will retry the Resolve-DnsName operation in order to ensure
its success.
=> images: Adds retry for Resolve-DnsName

images/InstallDependencies.ps1, images/Utils.ps1, images/etcd/Dockerfile, images/sample-apiserver/Dockerfile, images/sample-apiserver/sample-apiserver.golnk
Adds the following images:
- etcd
- sample-apiserver
Both images are required by the test: ``[sig-api-machinery] Aggregator Should be able to support the 1.10 Sample API Server using the current Aggregator [Conformance]``
=> Adds the etcd and sample-apiserver images

images/image-repo-list
The PR [1] introduced a new configurable registry for etcd images. The default etcd image does not have Windows support, so we have to use our e2eteam repo instead.
[1] https://github.com/kubernetes/kubernetes/pull/74666
=> Adds  etcdRegistry to image-repo-list

job-templates/kubernetes_release.json, job-templates/kubernetes_release_staging.json
Reverts kubernetes-sigs/windows-testing#34
That PR should have been held until we have a new AKS-Engine build supporting it. 
Here's the changelist we're waiting on: https://github.com/Azure/aks-engine/pull/599
=> Revert "Disable automatic updates"

images/InstallDependencies.ps1
Some binaries fail to build due to missing dependencies.
Adding them to InstallDependencies.ps1 solves the issue.
Partially Fixes #30
=> Adds new dependencies to InstallDependencies.ps1

images/BuildImageManifestLists.ps1, images/BuildImages.ps1, images/Utils.ps1
At the moment, the go executables are built only once; if the executable
is already found, they will not be rebuilt.
If the go sources are modified, the executables would need to be rebuilt
manually or deleted before recreating the images.
This commit passes the $Recreate flag to the BuildGoFiles function,
which will now rebuild the executables if true.
=> tests: Recreates go executables if Recreate is true

images/Utils.ps1
The image was used by a test that was deleted some time ago. (should create and stop Zookeeper, Nimbus and Storm worker servers, which existed in test/e2e/examples.go).
Since that test was deleted, the image is no longer needed.  The image was WIP, and its Dockerfile wasn't committed.
Fixes #31
=> Removes zookeeper DockerImage

images/Utils.ps1
The --purge argument will cause the manifest list to be deleted after it was pushed, allowing a new, fresh, and up to date manifest list to be created next time the BuildImageManifestLists.ps1 is called.
Fixes:  #40
=> images: Adds --purge to docker manifest push command

images/cassandra/Dockerfile
Cassandra 3.11.3 has been unpublished, so the image now fails to
build.
Updates the downloaded binary to a newer version.
Partially Fixes: #30
=> images: Updates Cassandra binary version to 3.11.4

job-templates/kubernetes_release_staging.json
This reverts commit 709d830022f320825f4851e7eda66c884fba0d4d.
Reason: staging job fails, azure-cni v1.0.18 does not seem to work.
=> Revert "Update staging template to include azure-cni 1.0.18"

job-templates/kubernetes_release_staging.json
Update staging template for aks-engine based jobs. This PR update Docker version. It also removes the custom azure-cni version as the released version v1.0.18 is already contained in newer versions of aks-engine.
=> Update staging template docker version.

images/Utils.ps1, images/etcd/Dockerfile
Fixes issue #52 
Changed versioning to support both `v3.3.10` and `3.3.10`
Changed [path](https://github.com/kubernetes-sigs/windows-testing/commit/70911aa7949df762d885426a95858d461603c811#diff-a82fdf09246795a2a5daca6708f7aa5eR22) of `etcd.exe` from images/etcd/Dockerfile to fit the [new path](https://github.com/kubernetes/kubernetes/commit/175dcdb3d67dddefcd35e1f7be7cab7e3c3f3483?diff=split#diff-c944d1288edcaf37beebab811603bfd8R220)
=> Fixed versioning and executable path

job-templates/kubernetes_release_staging.json
The custom version was removed as the staging job was updated
to use aks-engine version 0.34.0 that defaults azure-cni to v1.0.18.
However, since that version of aks-engine does not properly handle
custom extensions scripts we have to revert to a known working
aks-engine version for the job, via:
https://github.com/kubernetes/test-infra/pull/12238
=> Add custom azure-cni version back to staging template.

job-templates/kubernetes_release_staging.json
Staging job continues to fail consistently. We set last known working windows image version ( "1809.0.20190314" : kernel version: 10.0.17763.379 ) in a further attempt to bring the job back to the last known working state.
=> Set last known working Windows version for staging

images/Utils.ps1, images/iperf/Dockerfile
The image is required for the tests:
[sig-network] Networking IPerf IPv6 [Experimental][Feature:Networking-IPv6] [Slow] [Feature:Networking-Performance] should transfer ~ 1GB onto the service endpoint 1 servers (maximum of 1 clients)
[sig-network] Networking IPerf IPv4 [Experimental][Feature:Networking-IPv4] [Slow] [Feature:Networking-Performance] should transfer ~ 1GB onto the service endpoint 1 servers (maximum of 1 clients)
The tests are running /bin/bash, so basing the image on busybox is required.
=> images: Adds iperf image

images/Utils.ps1, images/dnsutils/Dockerfile, images/jessie-dnsutils/Dockerfile
Some images require a custom DNS server. Previously, it was using dnsmasq, which is Linux-specific, but it has been replaced with CoreDNS, which can also run on Windows.
This commit adds CoreDNS to the dnsutils and jessie-dnsutils images.
=> images: Adds CoreDNS to dnsutils and jessie-dnsutils

images/Utils.ps1, images/httpd/Dockerfile, images/httpd/httpd.conf
A recent commit to the Kubernetes E2E tests introduced the usage of the httpd image, as it has IPv6 support.
We'll have to build that images as well.
There are 2 versions of httpd that are being used in E2E tests.
=> images: Adds httpd images

images/Utils.ps1, images/nonroot/Dockerfile
The nonroot image will be useful for the RunAsUserName related E2E tests.
=> images: Adds nonroot image

job-templates/kubernetes_release_staging.json
sshEnabled doesn't currently work with June Windows Image. Removing until we fix the issue in aks-engine.
=> Remove sshEnabled from staging template

images/httpd/Dockerfile
Copies index.html to htdocs in Dockerfile.
Fixes: https://github.com/kubernetes-sigs/windows-testing/issues/93
=> Copy index.html to right path in httpd image

images/image-repo-list-ws1803, images/image-repo-list-ws2019
We previously had separate repo list files per Windows version, but since we've added manifest list support to the build scripts, they are no longer necessary, only the image-repo-list file, containing just the e2eteam registry, should be used.
=> Removes image-repo-list extra files

job-templates/kubernetes_master.json, job-templates/kubernetes_release_staging.json
Update orchestrator version to 1.16 to reflect support in newer aks-engine versions.
=> Update orchestrator version for master templates.

extensions/gmsa-dc/README.md, extensions/gmsa-dc/v1/Promote-DC.ps1, extensions/gmsa-dc/v1/Setup-gMSA.ps1, extensions/gmsa-dc/v1/supported-orchestrators.json, extensions/gmsa-dc/v1/template-link.json, extensions/gmsa-dc/v1/template.json, extensions/gmsa-member/README.md, extensions/gmsa-member/v1/Join-Domain.ps1, extensions/gmsa-member/v1/supported-orchestrators.json, extensions/gmsa-member/v1/template-link.json, extensions/gmsa-member/v1/template.json
**Reason for Change**:
Enables automated testing of GMSA feature.
**Notes**:
This extension enables automated e2e testing of the GMSA feature usable by Windows nodes.  It is recommended to run this extension against a pool of one server.  The extension will create the Active Directory domain, the Domain Controller, and the Group Managed Service Account for testing.
This PR was moved to this repo from AKS.
=> test: Creates AD Domain for GMSA e2e testing

extensions/gmsa-coredns/README.md, extensions/gmsa-coredns/v1/supported-orchestrators.json, extensions/gmsa-coredns/v1/template-link.json, extensions/gmsa-coredns/v1/template.json, extensions/gmsa-coredns/v1/update-coredns.sh
This extension for AKS updates the coredns config on the master node so that resources can find the Active Directory Domain, Domain Controller, and members.
This work in conjunction with the gmsa-dc and gmsa-member extensions in order to facilitate automated e2e testing for the gmsa feature.
=> Update coredns config for gmsa

job-templates/kubernetes_release_staging.json
Removing WindowsRunAsUserName feature gate because it is moved to beta for 1.17
This PR should be held until after these PRs are merged:
- https://github.com/kubernetes/kubernetes/pull/84882
- https://github.com/kubernetes/test-infra/pull/15173
=> Removing WindowsRunAsUserName feature gate in kubernetes_release_staging job

gce/0001-Build-windows-biniaries-when-running-make-quick-rele.patch, gce/LICENSE, gce/OWNERS, gce/README.md, gce/prepull.yaml, gce/run-e2e.sh
Our Windows-on-GCE test jobs still depend on https://github.com/yujuhong/gce-k8s-windows-testing, which predates this repository. This PR migrates that repository here and adds a new OWNERS and README file.
The benefits are discoverability and perhaps consistency between Windows test environments (e.g. when the manifest of test containers for AKS is updated we can update the GCE manifest as well).
cc @yliaog @YangLu1031
=> Import gce-k8s-windows-testing repository

gce/prepull-1.14.yaml, gce/prepull-1.15.yaml, gce/prepull-1.16.yaml, gce/prepull-1.17.yaml, gce/prepull-1.18.yaml, gce/prepull-head.yaml, gce/run-e2e.sh
Some of our Windows GCE test jobs have been timing out more frequently and I noticed that the list of containers that we prepull onto the nodes has not been updated in a while. This PR makes the following changes:
- Forks the prepull.yaml file into version-specific files. The containers used for each version were determined by examining the build.txt output files from current test jobs.
- Updates run-e2e.sh to use an environment variable to select which prepull manifest to use. I'll follow up with a test-infra PR to set this variable for each of our test jobs.
- Switches from initContainers to just containers in the DaemonSet. initContainers will halt if any container fails to pull + start. Replaces the container run commands with a command that will infinitely loop rather than exiting, …
=> Update prepulled Windows test containers

gce/prepull-1.14.yaml, gce/prepull-1.15.yaml, gce/prepull-1.16.yaml, gce/prepull-1.17.yaml, gce/prepull-1.18.yaml
Removes some containers that are believed to be unused based on better test log filtering and comments on PR #126. Adds some containers that were detected by looking at multiple test logs.
Once https://github.com/kubernetes/kubernetes/pull/88022 gets merged it will let us see the list of containers present on the nodes at the end of the e2e test run, which I'll then compare against these manifests to detect if I've missed prepulling any containers. Unfortunately there's not an easy way to detect prepulled containers that need to be pruned.
=> Update prepulled containers again

gce/load-test.sh, gce/loadtest-prepull.yaml
Need to schedule prometheus server pods on linux nodes, so cannot taint linux node as before. Use nodeSelector & Tolerations to prepull test image on windows node.
=> Using nodeSelector & Tolerations to prepull test image

images/image-repo-list
We've recently enabled the Image Promoter to run over the k/k test images. It promotes the images into a different registry to the usual e2eRegistry, so a separate entry was needed.
This adds promoterE2eRegistry to the image-repo-list, which we now need.
=> Adds promoterE2eRegistry to image-repo-list

OWNERS
Mark and Ernest are also approvers on the SIG-Windows prow configs - https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/sig-windows/OWNERS
Those jobs reference the [job-templates](https://github.com/kubernetes-sigs/windows-testing/tree/master/job-templates) here, so they need access to update them too.
=> Add two more people for aks-engine & Windows

gce/run-e2e.sh
This means we only wait as long as we need to, instead of always the maximum
/assign @pjh
=> Use kubectl wait instead of sleeps in gce/run-e2e

extensions/gmsa-coredns/v1/update-coredns.sh, extensions/master_extension/v1/win-e2e-master-extension.sh
The latest kubectl built from k/k master branch causes kubectl commands to fail due to a new validation logic introduced in kubernetes/kubernetes@b19ad9e. 
```
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:
1. Via the command-line flag --kubeconfig
2. Via the KUBECONFIG environment variable
3. In your home directory as ~/.kube/config
```
This PR explicitly set kubeconfig when using kubectl to avoid this problem.
/hold
=> fix: explicitly set kubeconfig when using KUBECTL in CSE

gce/run-e2e.sh
@pjh another tiny change, I'm trying to call run-e2e.sh directly from my script (not through kubernetes_e2e.py) and having issues with `--ginkgo.focus` losing its quotes. It seems that quoting `"$@"` here is needed to preserve the quotes in the flags I'm trying to pass through.
=> Quote splatted args to ginkgo-e2e

gce/hack-run-e2e.sh
hack-run-e2e.sh is exactly the same as run-e2e.sh except that $@ is *not* quoted. The quote was added in https://github.com/kubernetes-sigs/windows-testing/pull/142. 
this pr is to check whether the e2e test cases selection issue is due to https://github.com/kubernetes-sigs/windows-testing/pull/142
=> added hack-run-e2e.sh

job-templates/kubernetes_storage.json
This API model will be used for in-tree storage e2e tests on Windows clusters.
=> Add an API model for in-tree storage e2e tests on Windows clusters

scripts/win-ci-logs-collector.sh
We see the following message when trying to scp some logs on Azure: `protocol error: filename does not match request`
We add -T flags to scp on Windows to fix this.
=> Add -T flag to scp

job-templates/kubernetes_storage.json
Updating cluster definition used for testing in-tree storage drivers to https://github.com/kubernetes-csi/csi-proxy on Windows nodes.
=> Install csi-proxy for kubernetes_storage.json

job-templates/kubernetes_containerd.json
Adding an aks-engine cluster definition for running tests against a windows + containerd cluster.
=> Adding aks-engine cluster definition for containerd

gce/load-test.sh, gce/loadtest-prepull.yaml, gce/prepull-1.18.yaml
Companion to https://github.com/kubernetes/kubernetes/pull/89601.
- Updates prepulled container manifest for e2e tests. I verified this works against both LTSC (2019) and SAC (1909) clusters with March node images using `kubectl create -f gce/prepull-1.18.yaml`.
- Updates loadtest's prepulled pause version from 1.1.0 to 1.2.0.
- Updates load-test.sh to look more like run-e2e.sh.
cc @adelina-t
=> Update GCE files for switch to March node images

gce/hack-run-e2e.sh, gce/load-test.sh, gce/run-e2e.sh
If prepulled containers fail to run, `describe pods` should show which containers are failing.
This will help current failures in our GCE Windows tests, where the test log only shows:
```
...
+ kubectl wait --for=condition=ready pod -l prepull-test-images=e2e --timeout 30m
timed out waiting for the condition on pods/prepull-test-containers-gxjhh
timed out waiting for the condition on pods/prepull-test-containers-mqf4j
timed out waiting for the condition on pods/prepull-test-containers-r96tp
+ kubectl get pods -o wide
NAME                            READY   STATUS             RESTARTS   AGE   IP          NODE                                           NOMINATED NODE   READINESS GATES
prepull-test-containers-gxjhh   14/17   CrashLoopBackOff   85         92m   10.64.2.3 …
```
=> Describe pods after waiting for prepull

gce/prepull-1.18.yaml
This is currently failing to prepull in our test jobs at head:
```
httpd-2438:
Container ID:  docker://                                                    6ae484f4093b6c8cba653c7a56f6b052616c6a5ca3de2e707a83199ca0976a01
Image:         e2eteam/httpd:2.4.38-alpine
Image ID:      docker-pullable://e2eteam/httpd@sha256:                      0cf7810e6cf7da9f0d0fe45ce05a24d15014da8668cfa70fb18b9e1f01604800
Port:          <none>
Host Port:     <none>
Command:
cmd.exe
/c
ping -n 1800 127.0.0.1 >NUL
State:          Waiting
Reason:       CrashLoopBackOff
Last State:     Terminated
Reason:       Error
Exit Code:    1
```
=> Remove httpd:2.4.38-alpine from prepull list

gce/hack-run-e2e.sh, gce/load-test.sh, gce/run-e2e.sh
We discovered that kubectl wait will actually timeout only after timeout*number of objects being waited on. So if you wait on 3 pods specifying a timeout of 10m, it will actually wait 30m.
`kubectl sleep --timeout -1s` will wait a week, so plausibly "forever".
Fixes #158
kubernetes/kubectl#754
/assign @pjh
I checked and ensured that the kubekins image has `timeout` in it.
=> Wrap kubectl wait with coreutils timeout

job-templates/kubernetes_storage.json
The replicas of csi-azuredisk-controller and csi-azurefile-controller is 2. The controller can only run on Linux. So in the windows e2e tests, need two Linux machines at least. Otherwise, `helm install azuredisk-csi-driver` will fail.
For ask-engine, masters have count value of 1, 3, or 5 masters.
So here I set to 3.
=> chore: set the count of master to 3 in windows cluster

job-templates/kubernetes_storage.json
In order to enhance the robustness, use csi-proxy v0.1.0 instead of master version. 
/ping @andyzhangx @marosset @chewong
=> chore: use csi-proxy v0.1.0

job-templates/kubernetes_containerd_hyperv.json
This adds job-templates/kubernets_contaienrd_hyperv.json which configures containerd to configures the default pod sandbox to use hyperv isolation for WS2019 containers as the default.
=> Adding job template to test containerd with hyperv isolation enabled

job-templates/kubernetes_containerd.json
Updating containerd test passses on Azure to use a .zip with containerd/depenancies built nightly from master branches.
Github actions template - https://github.com/marosset/windows-cri-containerd/blob/master/.github/workflows/windows-cri-containerd.yml
=> ci: use nightly builds of containerd/hcsshim for Azure test passes

job-templates/kubernetes_2004_master.json
This adds an aks-engine template for windows version 2004 config which will be used by the test job to be configured in https://github.com/kubernetes/test-infra to create test signal for Windows SAC version 2004.  sig-windows discussed added support for 2004 in last [sig-windows meeting](https://github.com/kubernetes/community/tree/master/sig-windows) on June 23 2020.
=> Add 2004 test config

job-templates/kubernetes_containerd.json
Named pipe mount support merged into containerd/cri which is required for CSI proxy to function.
=> ci: Install csi-proxy for aks-engine containerd deployments

extensions/master_extension/v1/win-e2e-master-extension.sh, extensions/master_extension_prepull/v1/win-e2e-master-extension.sh
Fixes timeout on control nodes introduced with https://github.com/kubernetes-sigs/windows-testing/pull/178
`Timeout`  cmd spawns sub process and needs vars exported otherwise end up with error message during provisioning becuase `KUBECTL` varaible is missing
```
bash: line 1: get: command not found
bash: line 4: get: command not found
node/k8s-master-12396028-0 tainted
node/k8s-master-12396028-0 labeled
daemonset.apps/prepull created
daemonset.apps "prepull" deleted
```
which results in errors like:
```
Jul  8 08:21:43.397: FAIL: Error waiting for all pods to be running and ready: 2 / 10 pods in namespace "kube-system" are NOT in RUNNING and READY state in 10m0s
```
```
Jul  8 00:34:49.082: INFO: >>> kubeConfig: /root/tmp013712723/kubeconfig/kubeconfig.eastus2.json
Jul  8 00:34:49.104: …
```
=> Fix for timeout spawning sub process and needs vars exported

job-templates/kubernetes_containerd_hyperv.json
This does two things:
- bumps containerd version for enabling emptry-dir
- make the vm size larger for hyperv.  Currently getting 10 pods onto a smaller sized vm is not feasible due to the nature of the hyperv containers using compute and memory to create the container "vm". 
The hyperv tests at were failing with the error and this version resolves the error.
```
Jul 22 23:14:01.571: FAIL: Unexpected error:
<*errors.errorString | 0xc0030ac270>: {
s: "expected pod \"var-expansion-e6bb6c54-358e-4918-9fdd-d20e81717ccf\" success: Gave up after waiting 5m0s for pod \"var-expansion-e6bb6c54-358e-4918-9fdd-d20e81717ccf\" to be \"Succeeded or Failed\"",
}
expected pod "var-expansion-e6bb6c54-358e-4918-9fdd-d20e81717ccf" success: Gave up after waiting 5m0s for pod …
```
=> Update to new hyperv package and bump vm size

README.md
Update the repo list url for anyone getting started.  The e2e repo list now uses multi arch manifests so no need to specify the version
=> update image repo list location in readme

images/image-repo-list
We've added the private image ``e2eprivate/windows-nanoserver:v1``. The image is a manifest list which contains images for 1809, 1903, 1909, 2004, and it will be used for the test ``[k8s.io] Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret [NodeConformance]``.
Fixes Issue: https://github.com/kubernetes/kubernetes/issues/93048
=> Adds gcAuthenticatedRegistry to image-repo-list

images/image-repo-list-2004
We still need to keep the image-repo-list as is. The pull requests that can configure the tests to use a custom docker config.json file was merged in 1.19, so it wouldn't work for earlier releases.
Creates image-repo-list-2004 for 2004 jobs.
=> Creates a separate image-repo-list file for 2004

job-templates/kubernetes_2004_containerd.json, job-templates/kubernetes_2004_containerd_hyperv.json, job-templates/kubernetes_containerd_hyperv.json
This pr updates:
- hyperv package to 0.8 - includes fix for the read only volume mount test
- gives 2004 hyperv vms larger size
- disables csi-proxy for 2004 tests since not being used
=> Update Hyperv package to 0.8

job-templates/kubernetes_containerd.json, job-templates/kubernetes_containerd_hyperv.json, job-templates/kubernetes_csi_proxy.json, job-templates/kubernetes_in_tree_volume_plugins.json, job-templates/kubernetes_release_staging.json
The tests using windows vhd's are failing due to old images not being available. 
can verify these images are available by running:
```
az vm image list --all --publisher microsoft-aks --offer aks-windows --output table
Offer        Publisher      Sku                                             Urn                                                                                         Version
-----------  -------------  ----------------------------------------------  ------------------------------------------------------------------------------------------  -----------------
aks-windows  microsoft-aks  2019-datacenter-core-smalldisk                  microsoft-aks:aks-windows:2019-datacenter-core-smalldisk:17763.805.191025                   17763.805.191025
aks-windows  microsoft-aks …
```
=> update to latest aks-windows image versions to fix failing jobs

job-templates/kubernetes_2004_containerd_hyperv.json, job-templates/kubernetes_containerd_hyperv.json
Updating  aks-engine job templates for testing Hyper-V isolated containers.
Aks-engine v0.55.0 now has support for specifying what runtime classes should be configured on the node.
https://github.com/Azure/aks-engine/blob/master/docs/topics/features.md#hyper-v-support
This needs to merge After
=> Updating aks-engine job templates for hyper-v isolated jobs

helpers/hyper-v-mutating-webhook/deployment.yaml, helpers/hyper-v-mutating-webhook/webhook.go
Also updating image refs for all containers and init containers in pods
=> Updating hyper-v mutating webhook to account for e2e.test doesn't add node selectors to pods

job-templates/kubernetes_docker_gpu_master.json
I verified that the Azure subscription that aks-engine test passes run in can create NC6 VMs in **eastus** region.
I also verified I could start containers with GPD devices attached with
`docker run --isolation process --device class/5B45201D-F2F2-4F3B-85BB-30FF1F953599 mcr.microsoft.com/windows:1809`
https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/gpu-acceleration
This is needed to set up presubmit/periodic jobs for https://github.com/kubernetes/kubernetes/pull/93948
=> Adding aks-engine template for docker + GPU test jobs

job-templates/kubernetes_release_1_17.json
https://testgrid.k8s.io/provider-azure-windows#aks-engine-azure-1-17-windows was waiting for 2 agent nodes in the master extension script but the cluster only had 1 agent.
=> fix: set agent count to 2 for 1.17 API model

helpers/hyper-v-mutating-webhook/deployment.yaml, helpers/hyper-v-mutating-webhook/webhook.go
This unblock a few more tests such as 
* [k8s.io] Variable Expansion should verify that a failing subpath expansion can be modified during the lifecycle of a container
which modify pod specs triggering the mutating webhook again
=> Updating mutating hyperv webhook to check tags before adding single arch image suffix

job-templates/kubernetes_1903_master.json, job-templates/kubernetes_1909_master.json, job-templates/kubernetes_2004_containerd.json, job-templates/kubernetes_2004_master.json, job-templates/kubernetes_containerd_1_19.json, job-templates/kubernetes_containerd_1_19_serial.json, job-templates/kubernetes_containerd_csi_proxy.json, job-templates/kubernetes_containerd_master.json, job-templates/kubernetes_containerd_master_serial.json, job-templates/kubernetes_csi_proxy.json, job-templates/kubernetes_docker_gpu_master.json, job-templates/kubernetes_in_tree_volume_plugins.json, job-templates/kubernetes_release_1_16.json, job-templates/kubernetes_release_1_17.json, job-templates/kubernetes_release_1_17_serial.json, job-templates/kubernetes_release_1_18.json, job-templates/kubernetes_release_1_18_serial.json, job-templates/kubernetes_release_1_19.json, job-templates/kubernetes_release_1_19_serial.json, job-templates/kubernetes_release_staging.json, job-templates/kubernetes_release_staging_serial.json
kube-apiserver is failing due to lack of --service-account-* so switched to use the aks-engine nightly was used which breaks the rest of the tests due to managed identity being used in aks-engine.
/assign @chewong @marosset
=> Set use managed explicitly

job-templates/kubernetes_1903_master.json, job-templates/kubernetes_1909_master.json, job-templates/kubernetes_2004_containerd.json, job-templates/kubernetes_2004_master.json, job-templates/kubernetes_containerd_hyperv.json, job-templates/kubernetes_containerd_master.json, job-templates/kubernetes_release_staging.json
Attempt to fix `Kubernetes e2e suite.[k8s.io] Probing container should be restarted with an exec liveness probe with timeout [NodeConformance]` by enabling ExecProbeTimeout feature gate, which is disabled by default by aks-engine.
=> fix: enable ExecProbeTimeout feature gate

job-templates/kubernetes_1903_1_18.json
fixes https://testgrid.k8s.io/provider-azure-windows#aks-engine-azure-windows-1903-1-18 since ExecProbeTimeout is not available in 1.18.
=> fix: remove ExecProbeTimeout feature flag for 1903 API model

job-templates/kubernetes_1909_master.json, job-templates/kubernetes_2004_master.json
The RunAsUserName feature gate has been GA since 1.18 and will be getting removing in v1.21 with https://github.com/kubernetes/kubernetes/pull/96531
=> Removing RunAsUserName feature gate from configs targeting master

images/image-repo-list-master
As we promoted more test images that are available for Windows nodes, I created `image-repo-list-master`, which uses the default `promoterE2eRegistry` in https://github.com/kubernetes/kubernetes/blob/master/test/utils/image/manifest.go#L78.
/cc @claudiubelu
=> test images: create image-repo-list-master

gce/prepull-1.19.yaml, gce/prepull-1.20.yaml, gce/prepull-1.21.yaml, gce/prepull-head.yaml
It's been a while since we updated the manifests for the test containers that should be [prepulled](https://github.com/kubernetes-sigs/windows-testing/pulls?q=is%3Apr+pjh+prepull) onto GCE Windows K8s nodes before e2e test jobs start. This PR adds prepull manifests for the versions currently tested on the [google-windows](https://testgrid.k8s.io/google-windows#gce-windows-2019-master&width=20) testgrid.
The comments in the prepull files include a `grep` command to run against `build-log.txt` from an e2e test run in order to generate a complete-ish list of the test containers used. I ran this for test output for 1.19, 1.20 and 1.21 to create this change.
At worst this change should have no effect on our test jobs; at best it may reduce some flakiness due to timeouts when pulling test …
=> Update prepull manifests for GCE Windows test jobs

job-templates/kubernetes_containerd_csi_proxy.json, job-templates/kubernetes_csi_proxy.json, job-templates/kubernetes_in_tree_volume_plugins.json
**What type of PR is this?**
/kind bug
Optionally add one or more of the following kinds if applicable:
**What this PR does / why we need it**:
Updates windows image version to use in the e2e test manifest. New windows version has mitigation for driver DaemonSet crashes.
**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/553
**Requirements**:
**Special notes for your reviewer**:
@andyzhangx Please review.
**Release note**:
```
none
```
=> fix: Use new windows server image to avoid driver daemonset failure

gce/hack-run-e2e.sh
This mimics the aksengine.go logic for downloading image-repo-list from a different location based on `KUBE_TEST_REPO_LIST_DOWNLOAD_LOCATION`. This will fix a bunch of test failures in the GCE Windows dashboards because of the missing jessie-dnsutils:1.4 image.
/sig windows
/priority important-soon
=> Support configurable image-repo-list sources in GCE Windows tests.

images/image-repo-list-2004, images/image-repo-list-master
Removed `dockerLibraryRegistry ` since it's removed in https://github.com/kubernetes/kubernetes/pull/98964, and all the dockerhub images have been migrated to `k8s.gcr.io/e2e-test-images`.
/hold
/assign @marosset 
/cc @claudiubelu
=> chore: remove dockerLibraryRegistry from image-repo-list

images/image-repo-list-2004, images/image-repo-list-master
The gcRegistry contains both the pause and etcd images. We should use the official pause image in testing, but the etcd image does not contain Windows support yet.
Related: https://github.com/kubernetes/kubernetes/pull/98926
=> Changes gcRegistry to gcEtcdRegistry

job-templates/kubernetes_1909_master.json, job-templates/kubernetes_containerd_hyperv.json, job-templates/kubernetes_containerd_master.json, job-templates/kubernetes_release_staging.json
Attempts to fix the following test case
```
Kubernetes e2e suite.[sig-auth] ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]
```
in https://testgrid.k8s.io/sig-release-master-informing#aks-engine-azure-windows-master-containerd. 
Looks like we need to prepend `https://` for `--service-account-issuer` but aks-engine doesn't do that currently (https://github.com/Azure/aks-engine/blob/master/pkg/api/defaults-apiserver.go#L104). If this fixes the test failure, I will open a PR against aks-engine.
=> fix: overwrite --service-account-issuer

gce/loadtest-prepull.yaml
**What type of PR is this?**
/kind cleanup
**What this PR does / why we need it**:
As part of the efforts described in this Issue: https://github.com/kubernetes/k8s.io/issues/1525 we are trying to move away from `gcp project gke-release`
Also the pause image was release with windows support as we can see in the merged or in k/k https://github.com/kubernetes/kubernetes/pull/98205
/assign @spiffxp @jayunit100
=> test: update pause-win image to the new one k8s.gcr.io/pause:3.4.1

images/image-repo-list-2004, images/image-repo-list-master
Temporarily pointing httpd registry to ACR to mitigate https://github.com/kubernetes/kubernetes/issues/99047.
=> chore: add gcHttpdRegistry in image-repo-list

images/image-repo-list-pr
This points `promoterE2eRegistry` back to `k8sprow.azurecr.io/kubernetes-e2e-test-images` for now to mitigate https://github.com/kubernetes/kubernetes/issues/99325 and potential test image issues until they are stable. Copied the following test images from k8s.gcr.io in preparation for this PR.
Image | Version
-- | --
Agnhost | 2.28
Sample-apiserver | 1.17.4
Etcd | 3.4.13-0
Jessie-dnsutils | 1.4
Kitten | 1.4
Nautilus | 1.4
Nonroot | 1.1
Resource-consumer | 1.9
This PR also adds `image-repo-list-pr`, which uses the default `promoterE2eRegistry` so we can test changes introduced to test images by PRs in k/k.
/cc @claudiubelu
=> fix: add image-repo-list-pr and add promoterE2eRegistry to image-repo-list-master

README.md, images/README.md, images/image-repo-list-2004
Ref: https://github.com/kubernetes/kubernetes/issues/99363.
Follow-up PR for https://github.com/kubernetes-sigs/windows-testing/pull/249.
Temporarily pointing `promoterE2eRegistry` in `image-repo-list-2004` to k8sprow.azurecr.io/kubernetes-e2e-test-images until https://github.com/kubernetes/kubernetes/issues/99325 and https://github.com/kubernetes/test-infra/issues/20884 are fixed.
/cc @jeremyje
=> docs: add readme to image-repo-list

images/image-repo-list-2004, images/image-repo-list-master, images/image-repo-list-pr
Removed unused entries from image_repo_list files:
- ``e2eRegistry``: The only image left in that registry is ``cuda-vector-add:1.0``, which is not Windows-specific.
- ``etcdRegistry``: Doesn't exist in ``kubernetes/utils/image/manifest.go``, there's only ``GcEtcdRegistry``.
- ``gcHttpdRegistry``: No longer needed, we've fixed the ``httpd`` image for Windows.
- ``hazelcastRegistry``: The test in which it was used  was removed in Kubernetes v1.13.
- ``sampleRegistry``: No images left in that registry.
- ``stormRegistry``: refers to the registry used for the storm-nimbus image. The test in which it was used  was removed in Kubernetes v1.13
- ``zookeeperRegistry``: same as ``stormRegistry``. There is a ``zookeeper-installer`` image that is currently in   the ``k8s.gcr.io/e2e-test-images`` …
=> Cleans up image repo lists

scripts/win-ci-logs-collector.sh
In a recent run a node didn't come online. The [log collection](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1374061007583842304) failed with:
```
Downloading log collector script to Windows machine 3474k8s001.
Warning: Permanently added 'kubetest-0nddyzc3.southcentralus.cloudapp.azure.com,20.188.89.181' (ECDSA) to the list of known hosts.
Authorized uses only. All activity may be monitored and reported.
Warning: Permanently added '3474k8s001' (ECDSA) to the list of known hosts.
Test-Path : Cannot bind argument to parameter 'Path' because it is null.
At C:\AzureData\k8s\kuberneteswindowsfunctions.ps1:23 char:19
+     if (Test-Path $global:CacheDir) {
+                   ~~~~~~~~~~~~~~~~
+ CategoryInfo          : …
```
=> Don't rely on the extracted files being on disk

job-templates/kubernetes_1909_master.json, job-templates/kubernetes_containerd_hyperv.json, job-templates/kubernetes_containerd_master.json, job-templates/kubernetes_release_staging.json
- removed `--service-account-issuer` flag from apiserver config since it's now the default for aks-engine.
- ~set `runUnattendedUpgradesOnBootstrap` to false so master nodes won't reboot during the test pass while using nightly aks-engine build (we are using aks-engine v0.60.0 to avoid this problem)~ (addressed by https://github.com/kubernetes/test-infra/pull/21320)
/assign @jsturtevant @marosset 
/hold
=> fix: remove service-account-issuer apiserver flag

job-templates/kubernetes_2004_containerd.json, job-templates/kubernetes_2004_master.json, job-templates/kubernetes_20h2_master.json, job-templates/kubernetes_containerd_csi_proxy.json, job-templates/kubernetes_containerd_hyperv.json, job-templates/kubernetes_containerd_master.json, job-templates/kubernetes_containerd_master_serial.json, job-templates/kubernetes_csi_proxy.json, job-templates/kubernetes_docker_gpu_master.json, job-templates/kubernetes_release_staging.json, job-templates/kubernetes_release_staging_serial.json
/hold
until mcr.microsoft.com/oss/kubernetes/kube-addon-manager:v9.1.5 is available.
=> fix: bump kube-addon-manager to v9.1.5

job-templates/kubernetes_2004_containerd.json, job-templates/kubernetes_2004_master.json, job-templates/kubernetes_20h2_master.json, job-templates/kubernetes_containerd_csi_proxy.json, job-templates/kubernetes_containerd_hyperv.json, job-templates/kubernetes_containerd_master.json, job-templates/kubernetes_containerd_master_serial.json, job-templates/kubernetes_csi_proxy.json, job-templates/kubernetes_docker_gpu_master.json, job-templates/kubernetes_release_staging.json, job-templates/kubernetes_release_staging_serial.json
Reverts kubernetes-sigs/windows-testing#267 in favor of using HEAD build of aks-engine.
=> Revert "fix: bump kube-addon-manager to v9.1.5"

README.md
The README referced having to build the images themselves which
is no longer true.
Signed-off-by: John Schnake <jschnake@vmware.com>
=> Update README regarding Windows images

job-templates/kubernetes_containerd_1_5.json, job-templates/kubernetes_containerd_master-hostprocess.json
This adds a model with appropriate alpha settings for Hostprocess.
It also has a containerd 1.5.2 build with a containerd-shim built from https://github.com/microsoft/hcsshim/pull/962
/sig windows 
/assign @chewong
=> Add model for hostprocess tests and containerd 1.5

gce/hack-run-e2e.sh, gce/run-e2e.sh
According to https://github.com/kubernetes/kubernetes/pull/102337, need to add `--disable-log-dump` to trigger log dump from test-infra instead of k/k. 
Relevant Slack discussion: https://kubernetes.slack.com/archives/C09QZTRH7/p1621986566037600.
=> Add --disable-log-dump flag to disable k/k log dump path

job-templates/kubernetes_containerd_1_5.json
The job at https://testgrid.k8s.io/sig-windows-master-release#aks-engine-windows-containerd-1-5-master is failing regularly due to bugs fixed in hcsshim which have not been released and merged to containerd. 
This updates the 1.5.x jobs to use the tip for both containerd and hcschim which should resolve the issue.
/sig windows
/assign @chewong 
/cc @claudiubelu @adelina-t
=> Update containerd 1.5 to use nightly builds

job-templates/kubernetes_containerd_1_19.json, job-templates/kubernetes_containerd_1_19_serial.json, job-templates/kubernetes_containerd_1_20.json, job-templates/kubernetes_containerd_1_20_serial.json, job-templates/kubernetes_containerd_1_21.json, job-templates/kubernetes_containerd_1_21_serial.json, job-templates/kubernetes_containerd_master-hostprocess.json, job-templates/kubernetes_containerd_master.json, job-templates/kubernetes_containerd_master_serial.json, job-templates/kubernetes_containerd_nightly.json
- Moving 1.21+ to containerd 1.5.4
- updating 1.19/1.20 to containerd 1.4.8
- Using builds from sig-windows-tools: https://github.com/kubernetes-sigs/sig-windows-tools/pull/157
Renames the template for containerd to nightly to reflect that is building from main branch not 1.5 branch.  Requires update to test-infra jobs
/sig windows
/cc @marosset @chewong 
/hold 
for test-infra jobs updates
=> Update containerd versions

job-templates/kubernetes_2004_containerd.json, job-templates/kubernetes_containerd_1_19.json, job-templates/kubernetes_containerd_1_19_serial.json, job-templates/kubernetes_containerd_1_20.json, job-templates/kubernetes_containerd_1_20_serial.json, job-templates/kubernetes_containerd_1_21.json, job-templates/kubernetes_containerd_1_21_serial.json, job-templates/kubernetes_containerd_1_22.json, job-templates/kubernetes_containerd_1_22_serial.json, job-templates/kubernetes_containerd_hyperv.json, job-templates/kubernetes_containerd_master-hostprocess.json, job-templates/kubernetes_containerd_master.json, job-templates/kubernetes_containerd_master_serial.json, job-templates/kubernetes_containerd_nightly.json, job-templates/kubernetes_release_1_19.json, job-templates/kubernetes_release_1_19_serial.json, job-templates/kubernetes_release_1_20.json, job-templates/kubernetes_release_1_20_serial.json, job-templates/kubernetes_release_1_21.json, job-templates/kubernetes_release_1_21_serial.json, job-templates/kubernetes_release_staging.json, job-templates/kubernetes_release_staging_serial.json
Updates:
- azure cni (has fix for [500ms startup time improvement](https://github.com/Azure/azure-container-networking/pull/966))
- update Windows vhds
- adds 1.22 job templates and removes 1.18 (only containerd 1.22 job templates- capz jobs have been added for 1.22)
/sig windows
/cc @marosset @chewong
=> Job dep updates

job-templates/kubernetes_2004_containerd.json, job-templates/kubernetes_2004_master.json, job-templates/kubernetes_20h2_master.json, job-templates/kubernetes_containerd_1_19.json, job-templates/kubernetes_containerd_1_19_serial.json, job-templates/kubernetes_containerd_1_20.json, job-templates/kubernetes_containerd_1_20_serial.json, job-templates/kubernetes_containerd_1_21.json, job-templates/kubernetes_containerd_1_21_serial.json, job-templates/kubernetes_containerd_1_22.json, job-templates/kubernetes_containerd_1_22_serial.json, job-templates/kubernetes_containerd_hyperv.json, job-templates/kubernetes_containerd_master-hostprocess.json, job-templates/kubernetes_containerd_master.json, job-templates/kubernetes_containerd_master_serial.json, job-templates/kubernetes_containerd_nightly.json, job-templates/kubernetes_docker_gpu_master.json, job-templates/kubernetes_release_1_19.json, job-templates/kubernetes_release_1_19_serial.json, job-templates/kubernetes_release_1_20.json, job-templates/kubernetes_release_1_20_serial.json, job-templates/kubernetes_release_1_21.json, job-templates/kubernetes_release_1_21_serial.json, job-templates/kubernetes_release_staging.json, job-templates/kubernetes_release_staging_serial.json
In #278  we noticed these api all have V1 versions available.  This removes them from the job specs.
/sig windows
=> Don't explicity enable old apis for api server

job-templates/kubernetes_containerd_master_serial.json, job-templates/kubernetes_release_staging_serial.json
The new hpa tests are failing: https://github.com/kubernetes/kubernetes/issues/104427
according to https://github.com/kubernetes/enhancements/tree/master/keps/sig-autoscaling/2702-graduate-hpa-api-to-GA#feature-enablement-and-rollback:
> The feature can be enabled by adding autoscaling/v2 to the --runtime-config flag: https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/apiserver/pkg/server/options/api_enablement.go#L45
/sig windows
=> Add autoscaling v2 features to apiserver

job-templates/kubernetes_in_tree_volume_plugins_csi_enabled.json
related to https://github.com/kubernetes/kubernetes/pull/104670, we will enable csi migration on k8s 1.23, need to enable csi drivers by default
=> enable csi drivers for in-tree driver test config

images/MirrorUpstreamK8sImgs.ps1
Related:
- Part of: https://github.com/kubernetes/k8s.io/issues/1522
gcr.io/kubernetes-e2e-test-images is deprecated and hasn't received new
image updates in quite some time
=> images: use k8s.gcr.io/e2e-test-images

job-templates/kubernetes_containerd_nightly.json, job-templates/kubernetes_release_staging.json, job-templates/kubernetes_release_staging_serial.json
Reverts kubernetes-sigs/windows-testing#291
we need to update https://github.com/kubernetes/test-infra/blob/master/kubetest/aksengine_helpers.go#L88 so the serialization/deserialization that happens in the prow jobs knows about the field.
Will revert this revert once those changes are made.
=> Revert "enabling accelerated networking for staging cluster definitions"

job-templates/kubernetes_containerd_nightly.json, job-templates/kubernetes_release_staging.json, job-templates/kubernetes_release_staging_serial.json
Reverts kubernetes-sigs/windows-testing#292
This should be safe to commit again since https://github.com/kubernetes/test-infra/pull/24310 merged.
=> Revert "Revert "enabling accelerated networking for staging cluster definitions""

extensions/master_extension/v1/win-e2e-master-extension.sh
Due to bug in provisioning in aks-engine that has become more frequent recently
This adds a debugging statement to see what pods are running at this time, as well as restarts the kube-addon manager so that it doesn't get stuck in a bad loop looking for "/etc/kubernetes/addons/init"
A restart when it is running successfully doesn't trigger any changes to already running pods managed by the addon manager
See https://github.com/Azure/aks-engine/issues/4753 for more details
/sig windows
=> Restart addonmanager

job-templates/kubernetes_containerd_csi_proxy.json
since the test framework would install CSI driver, should not enable CSI driver addon in aks-engine tests
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-azure-disk-windows-containerd/1468745205195739136/build-log.txt
```
helm install azuredisk-csi-driver charts/latest/azuredisk-csi-driver --namespace kube-system --wait --timeout=15m -v=5 --debug \
--set image.azuredisk.repository=k8sprow.azurecr.io/azuredisk-csi --set image.azuredisk.tag=v1.10.0-2a2f6fda4a387f4549735d8106fa6e9f56b5441c --set image.azuredisk.pullPolicy=Always --set driver.userAgentSuffix="e2e-test"  \
--set windows.enabled=true \
--set linux.enabled=false \
--set controller.runOnMaster=true \
--set controller.replicas=1 \
--set controller.logLevel=6 \
--set node.logLevel=6 \
--set …
```
=> not enable CSI driver addon in aks-engine tests

job-templates/kubernetes_containerd_csi_proxy.json
Reverts kubernetes-sigs/windows-testing#301
=> Revert "not enable CSI driver addon in aks-engine tests"

job-templates/kubernetes_containerd_1_23.json, job-templates/kubernetes_containerd_1_23_serial.json, job-templates/kubernetes_containerd_master.json
Hostprocess is on by default with 1.23+ so we should use the release that supports it
=> Use latest containerd 1.6 for 1.23+

job-templates/kubernetes_containerd_1_23_serial.json
The HPA scale resource tests are failing: https://testgrid.k8s.io/sig-windows-1.23-release#aks-engine-windows-containerd-serial-slow-1.23
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-1-23-windows-containerd-serial-slow/1479248775422676992
```
Message: "HorizontalPodAutoscaler.autoscaling \"rs\" is invalid: spec.metrics[0].containerResource: Required value: must populate information for the given metric source (only allowed when HPAContainerMetrics feature is enabled)",
```
We dropped this flag when creating the new job templates.  This re-adds the flag
/sig windows
=> Add feature flag so HPA scale tests pass in 1.23 jobs

job-templates/kubernetes_containerd_1_23.json
azure disk csi migration is already enabled by default on k8s 1.23
=> enable azure disk csi driver on 1.23 template

job-templates/kubernetes_containerd_1_23.json, job-templates/kubernetes_in_tree_volume_plugins.json
azure disk csi migration is already enabled by default from k8s 1.23
=> enable azure disk csi driver on Windows cluster

job-templates/kubernetes_20h2_master.json, job-templates/kubernetes_containerd_master.json, job-templates/kubernetes_containerd_master_csi_enabled.json, job-templates/kubernetes_containerd_master_serial.json, job-templates/kubernetes_containerd_nightly.json
Some Windows tests are still using aks-engine which likely needs to be updated to support having legacy service account token auto generation disabled.
This PR reverts SA token generation to previous behavior.
x-ref: https://github.com/kubernetes/enhancements/pull/2800/files
=> Disabling LegacyServiceAccountTokenNoAutoGeneration as mitigation to unblock windows testing on aks-engine

job-templates/kubernetes_20h2_master.json, job-templates/kubernetes_containerd_master.json, job-templates/kubernetes_containerd_master_serial.json
LegacyServiceAccountTokenNoAutoGeneration feature gate should be set for controller-manager, not cloud-controller-manager.
Fixes issues introduced by #312
=> Fixing LegacyServiceAccountTokenNoAutoGeneration feature gate flags in some configs

extensions/gmsa-dc/v1/Setup-gMSA.ps1
Creating a folder on Active Directory server for gmsa file reading and writing test case.
Resolving this comment: https://github.com/kubernetes/kubernetes/pull/108432#issuecomment-1058692639
=> Create remote folder for storage test

job-templates/kubernetes_containerd_csi_proxy.json, job-templates/kubernetes_containerd_hyperv.json
This PR reverts SA token generation to previous behavior.
Addresses the failures of the following jobs:
```
ci-kubernetes-e2e-azure-file-windows-containerd
ci-kubernetes-e2e-azure-disk-windows-containerd
ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd-hyperv-serial-slow
ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd-hyperv
```
Ref: https://github.com/kubernetes-sigs/windows-testing/pull/312
=> Adds LegacyServiceAccountTokenNoAutoGeneration=false feature gate

job-templates/kubernetes_containerd_hyperv.json
Currently, the HPA tests are failing in the ``aks-engine-windows-containerd-hyperv-serial-slow-master`` because this feature is not enabled.
x-ref: https://github.com/kubernetes/kubernetes/issues/109521
=> Enables HPAContainerMetrics for Hyper-V runs

gce/OWNERS, gce/run-e2e.sh
To utilize new -prepull-images=true with new runs (which is based on manifest). We need to skip this out-dated pre-pull if PREPULL_YAML is not set.
=> Run prepull only if PREPULL_YAML is specified

gce/prepull-1.22.yaml, gce/run-e2e.sh
The change adds the prepull list required for gce windows e2e runs. prepull-1.22.yaml is required as -prepull-images=true is only available for >= 1.23.
Validated the 1.22 changes with runs invoked locally for the following:
ci-kubernetes-e2e-windows-containerd-gce-1.22
ci-kubernetes-e2e-windows-20h2-containerd-gce-1.22
ci-kubernetes-e2e-windows-gce-1.22
ci-kubernetes-e2e-windows-20h2-gce-1.22 
This is required to add back the periodic jobs for gce windows.
[prepull-head.yaml]
=> Update prepull image lists

.gitignore, capz/readme.md, capz/run-capz-e2e.sh, capz/templates/windows-base.yaml, images/image-repo-list-private-registry
We needed more flexibility with templates and ability to install additional tooling for things like gmsa so we've developed a new script for Windows e2e using capz.  This script is a WIP so have using a few branches to run the job until it stable. This script does work locally.
=> sig-windows custom E2E script and template for cluster api provider azure

capz/templates/windows-base.yaml
In the most recent run https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows-2022/1542246779368509440 the health check triggered right when the node was being created, This caused the node to be marked for deletion and the tests to hang.
there is a new image being published with an updated cloudbase-init package where this shouldn't be needed.
=> Remove healthcheck which is causing issues

capz/run-capz-e2e.sh
the CI variable is being fixed and this uses the build from the nightly capz cli extension: https://github.com/Azure/azure-capi-cli-extension/releases/tag/az-capi-nightly
Signed-off-by: James Sturtevant <jstur@microsoft.com>
=> Small update to make this script work locally

capz/run-capz-e2e.sh
Signed-off-by: James Sturtevant <jstur@microsoft.com>
Fixes the WS2022 jobs that were timeout at 1hr: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows-2022-serial-slow/1550272043243540480
```
test/e2e/e2e_test.go:142
<< End Captured GinkgoWriter Output
Interrupted by Timeout
Here's a stack trace of all running goroutines:
goroutine 79 [running]:
```
from https://github.com/kubernetes/kubernetes/pull/109111: `ACTION REQUIRED: When running test/e2e via the Ginkgo CLI, the v2 CLI must be used and `-timeout=24h` (or some other, suitable value) must be passed because the default timeout was reduced from 24h to 1h. When running it via `go test`, the corresponding `-args` parameter is `-ginkgo.timeout=24h`. To build the CLI in the Kubernetes …
=> fix timeout for ginkgo v2

images/README.md, images/image-repo-list, images/image-repo-list-2004, images/image-repo-list-master
Updates:
- drops the repo list for WS2004 which is EOL.  
- Starting in 1.25 the only repo list required is `gcr.io/authenticated-image-pulling` for the private image used in the test `Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret [NodeConformance]` with  Windows server 2022.  
- drops the repo-list used for < 1.21
=> Update Repo lists 

scripts/prepare_env_windows.ps1
Currently, the unit tests job logs are filled with the download progression from choco install. We should trim them.
=> Adds --no-progress to choco

capz/run-capz-e2e.sh
Updates the `az capi` Azure CLI extension to [v0.1.1](https://github.com/Azure/azure-capi-cli-extension/releases/tag/v0.1.1), which should fix provisioning errors encountered recently.
=> Update az capi extension to v0.1.1

capz/run-capz-e2e.sh
Once capz https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2931 merges we will need this update since kube-proxy will be in kube-system.
=> kube-proxy should be in kube-system

job-templates/kubernetes_containerd_1_23.json, job-templates/kubernetes_containerd_1_23_serial.json, job-templates/kubernetes_containerd_1_24.json, job-templates/kubernetes_containerd_1_24_csi_enabled.json, job-templates/kubernetes_release_1_23.json
These include some HNS fixes which should clean up the SIG-Windows test signal
=> Updating Windows VHD used in aks-engine template to include 2022 11B updates

capz/templates/gmsa.yaml, capz/templates/windows-base.yaml
Signed-off-by: James Sturtevant <jstur@microsoft.com>
There were a few changes to the kubernetes registry between 1.25 and 1.26. When the images are unpacked from the older versions the images that are unloaded don't contain the correct tag and therefor aren't found when they are pull by the name.  
There is a bit more information in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2398. The script is a copy of https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/207ff80443e55db9a7e3857fe51da46842e4b99e/templates/test/ci/prow-ci-version/patches/kubeadm-bootstrap.yaml from cluster-api-provider-azure
=> Update the pre-kubeadm script to work with < 1.25

scripts/k8s_unit_windows.ps1
Previously, we added the kubeadm binary building to the unit test script, as it is needed for a few of the kubeadm unit tests, however, the binary was not build correctly.
=> unit tests: Fixes kubeadm binary build

capz/run-capz-e2e.sh
Fixes a bug that was introduced when felix-override manifests were removed from CAPZ.
=> Update az capi extension to v0.1.2

gce/loadtest-prepull.yaml, gce/prepull-1.21.yaml, gce/prepull-1.22.yaml, gce/prepull-head.yaml, images/MirrorUpstreamK8sImgs.ps1
/kind cleanup
/sig windows
Part of https://github.com/kubernetes/k8s.io/issues/4738
/assign @jsturtevant @claudiubelu @jayunit100
=> Replacing k8s.gcr.io refs with registry.k8s.io in k-sigs/windows-testing

scripts/prepare_env_windows.ps1
Kubernetes has switched to golang 1.20. Because of this, the unit tests runs have failures with the following note:
note: module requires Go 1.20
Updates the installed golang to 1.20.2
Sample job failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1635618795965911040
=> unit tests: Updates golang to 1.20.2

capz/gmsa/configuration/configure.go, capz/readme.md, capz/run-capz-e2e.sh
I have been running `run-capz-e2e.sh` locally a lot lately and don't need to wait for log collection so adding the ability to skip.
=> Add ability to skip log collection when running run-capz-e2e.sh locally

scripts/ci-k8s-unit-test.sh
The current image is deprecated, resulting in failures:
```
ERROR: (ImageVersionDeprecated) VM Image from publisher: MicrosoftWindowsServer with - Offer: WindowsServer, Sku: 2022-datacenter-smalldisk-g2, Version: 20348.524.220201 is deprecated.
```
Example: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1643230608895250432
=> Updates the Windows image used for unit tests

capz/templates/gmsa.yaml, capz/templates/windows-base.yaml
WindowsHostProcessContainers was enabled by default in v1.23 and went stable in v1.26
https://github.com/kubernetes/kubernetes/pull/117570 removes the feature-gate
/sig windows
=> Removing references to WindowsHostProcessContainers feature-gate

capz/run-capz-e2e.sh
The script changes directories to the capz dir so we need to make sure SCRIPT_ROOT is an absolute path so we can find the cluster templates
=> ensure SCRIPT_ROOT in run-capz-e2e.sh is an absolute path

capz/run-capz-e2e.sh
PWD is set to the capz repo but we want to use the image-repo-list file from this repository
=> Use image-repo-list-private-registry from windows-testing repo

capz/templates/gmsa-pr.yaml, capz/templates/pr/patches/kubeadm-bootstrap-control-plane-pr.yaml, capz/templates/windows-pr.yaml
This is to work around an issue where kube-proxy DS updates are getting reverted after kubelet restart
=> Updating control-plane bootstrap script for PR jobs to update kube-proxy image after kubelet restart

capz/run-capz-e2e.sh
Use new calico version in az capi extension
/hold
Until https://github.com/Azure/azure-capi-cli-extension/pull/196 merges. This if for testing the package in the PR
=> Use new calico version in az capi extension

capz/templates/gmsa-ci.yaml, capz/templates/gmsa-pr.yaml, capz/templates/windows-base.yaml, capz/templates/windows-ci.yaml, capz/templates/windows-pr.yaml
This PR enables use run run nodeLogQuery e2e tests in upstrate PROW jobs.
NodeLogQuery requires both a feature gate and a kubelet config value (in the conf file) to be set.
For test clusters where we want to enable this alpha feature we will update the `NODE_FEATURE_GATE` env var to include `NodeLogQuery=true` and then the new post-kubeadm action will inspect the feature gates used to start the kubelet and append the correct setting if needed
/sig windows
/assign @jsturtevant @aravindhp
=> Adding a post-kubeadm action to write EnableLogQuery=true to kubelet config if needed

capz/templates/gmsa-ci.yaml, capz/templates/gmsa-pr.yaml, capz/templates/windows-base.yaml, capz/templates/windows-ci.yaml, capz/templates/windows-pr.yaml
/hold for CI jobs
Hopefully this will address some recent issues such with coredns not starting on the CP node for windows test passes
=> Updating control-plane os from Ubuntu 18.04 LTS to 22.04 LTS

capz/run-capz-e2e.sh, capz/templates/gmsa-ci.yaml, capz/templates/gmsa-pr.yaml, capz/templates/windows-base.yaml, capz/templates/windows-ci.yaml, capz/templates/windows-pr.yaml
Updating run-capz-e2e.sh to deploy clusters with an out of tree cloud provider
Fixes #367 
/sig windows
=> Updating templates used by az capi to use external cloud provider

scripts/ci-k8s-unit-test.sh
The unit test jobs are currently failing, seemingly before the ``az`` client is set up. We don't have a lot of information about what is happening in the script.
Setting the ``set -x`` option will at least log the parts of script that have run.
=> Adds set -x option for unit test script

.github/workflows/capz.yml, capz/gmsa/configuration/configure.go
Fixing go lint CI issues
I'm following recommendations from
https://github.com/golangci/golangci-lint-action/issues/677
and
https://github.com/golangci/golangci-lint-action/pull/704/files
=> Fixing run-lint github workflows

capz/templates/gmsa-ci.yaml, capz/templates/gmsa-pr.yaml, capz/templates/windows-base.yaml, capz/templates/windows-ci.yaml, capz/templates/windows-pr.yaml
Adding extra logging in replace-containerd.ps1 to see if any containerd files are locked during upgrade process
/hold
=> Adding logging into replace-containerd.ps1

capz/run-capz-e2e.sh
the serial slow jobs are failing due to not finding the kubeconfig.  It appears one of the scripts moves a directory but doesn't traverse back. We can fix this and avoid it in the future by using kubeconfig in well know location.
/sig windows
=> Always use same location for kubeconfig

capz/templates/gmsa-ci.yaml, capz/templates/gmsa-pr.yaml, capz/templates/windows-base.yaml, capz/templates/windows-ci.yaml, capz/templates/windows-pr.yaml
These are needed to get the VPA tests running in CAPZ created clusters in PROW
=> Allow for setting kube-apiserver and kube-scheduler features gates for VPA tests

capz/run-capz-e2e.sh
Logging the version of e2e.test used when run-capz-e2e.sh is run
=> Updating run-capz-e2e.sh to log e2e.test version

capz/run-capz-e2e.sh, capz/templates/gmsa-pr.yaml, capz/templates/pr/patches/kubeadm-bootstrap-control-plane-pr.yaml, capz/templates/pr/patches/kubeadm-bootstrap-windows-pr.yaml, capz/templates/windows-pr.yaml
/hold for local testing
This is needed so the Windows PR jobs do not get broken by https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4172
=> updating capz templates to set AZURE_BLOB_CONTAINTER_NAME for azure storage account used for PR artifacts

capz/run-capz-e2e.sh
Updates the calico version to latest released version
/hold
~using nightly to debug https://github.com/containerd/containerd/issues/9037~
=> Update calico and containerd default versions

capz/run-capz-e2e.sh
Add environment variables needed for e2e tests to SSH into nodes. This will be needed for the NodeLogViewer e2e tests to run.
Depends on https://github.com/kubernetes/kubernetes/pull/121708/
=> capz: Add env vars for SSH access

capz/run-capz-e2e.sh
https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/2a4f053b04bd5f84bda392d4e396912ac84ac7aa made some changes where artifacts built for CI jobs always use `kubernetes-ci` as the as the storage container name.
This PR updates run-capz-e2e.sh so we no longer use JOB_NAME too
=> Don't use JOB_NAME when fetching e2e.test in capz-run-e2e.sh

capz/templates/gmsa-ci.yaml, capz/templates/gmsa-pr.yaml, capz/templates/windows-base.yaml, capz/templates/windows-ci.yaml, capz/templates/windows-pr.yaml
Add a script to the KubeadmControlPlane that adds the enableSystemLogQuery option to the kubelet config if the NodeLogQuery feature flag is set
=> capz/templates: Allow enabling the NodeLogQuery feature

capz/Makefile, capz/run-capz-e2e.sh, capz/templates/ci/kustomization.yaml, capz/templates/ci/patches/market-place.yaml, capz/templates/shared-image-gallery-ci.yaml, capz/templates/sig/kustomization.yaml, capz/templates/sig/patches/shared-gallery.yaml
This sets up testing scripts for the Windows Annual channel https://techcommunity.microsoft.com/t5/windows-server-news-and-best/windows-server-annual-channel-for-containers/ba-p/3866248
The image is not in the azure market place, so currently need to [download and convert it to VHD](https://gist.github.com/thecloudtaylor/c6b551f24c198ebdaba6d8eca429bae8) and upload it to an Azure SIG.  [Image builder](https://github.com/kubernetes-sigs/image-builder/pull/1353) can then use this to build a CAPI ready image
/sig windows
/hold 
I've changed the base template here to force the CI in this PR to test this as some of the CI infra is new
=> Enable annual channel via Azure SIGs

capz/run-capz-e2e.sh
This is required as the e2e.test is run with --provider=skeleton
=> capz: export KUBE_SSH_KEY

scripts/prepare_env_windows.ps1
Kubernetes has switched golang to 1.21. Because of this, the unit test runs have failures with the following message:
note: module requires Go 1.21
Updates the installed golang to 1.21.6.
=> unit tests: Update golang to 1.21.6

capz/templates/gmsa-ci.yaml, capz/templates/gmsa-pr.yaml, capz/templates/shared-image-gallery-ci.yaml, capz/templates/windows-base.yaml, capz/templates/windows-ci.yaml, capz/templates/windows-pr.yaml
In preparation for removal of in-tree cloud provider: https://github.com/kubernetes/kubernetes/pull/122857 we need to remove this flag (https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4436)
/sig windows
=> Remove depreciated flag in move to external cloud-provider

capz/templates/ci/patches/kubeadm-bootstrap-windows-ci.yaml, capz/templates/gmsa-ci.yaml, capz/templates/shared-image-gallery-ci.yaml, capz/templates/windows-ci.yaml
This will let us continue to run the containerd nightly job
There have been several bug fixes since https://github.com/containerd/containerd/pull/9432 merged but still have a few more issues like https://github.com/containerd/containerd/pull/9717.  
Disabling so we can still get nightly signal on containerd 2.0 since we only use ctr for pre-pulling images and transfer service isn't enabled in CRI yet.
=> Disable transfer service until stabilizes in containerd

capz/run-capz-e2e.sh, capz/templates/shared-image-gallery-ci.yaml, capz/templates/sig/kustomization.yaml, capz/templates/sig/patches/kubeadm-bootstrap-ssh.yaml
Annual channel does not have functional ssh because it is missing a rule to allow port forwarding.  This adds the missing rule in the format that was previously created by the installer.  There may be a fix coming to the SSH installer at somepoint, when we can then remove this.
=> Add missing SSH rule for annual channel image

capz/run-capz-e2e.sh
#423 checked in a change that selected the wrong template by default and is causing failures on our testing jobs: https://github.com/kubernetes/kubernetes/issues/123650
=> Use windows ci as default

scripts/k8s_unit_windows.ps1
There are some breaking unit tests in ./pkg/proxy, which is why they were excluded. But now those tests are being skipped, so we're safe to run the rest.
=> Include proxy in Windows unit test runs

helpers/hyper-v-mutating-webhook/webhook.go
Updating the code for hyperv runtime to skip applying it to linux pods as linux doesnt support hyperv runtime.
These changes were locally tested by building the image and using that in hyperv deployment: we see two tests from the e2e pass once we add this check in:
1. Kubernetes e2e suite.[It] [sig-windows] Hybrid cluster network for all supported CNIs should have stable networking for Linux and Windows pods
2. Kubernetes e2e suite.[It] [sig-windows] Hybrid cluster network for all supported CNIs should provide Internet connection for Linux containers [Feature:Networking-IPv4]
=> Updating webhook.go to ensure hyperv is applied only to windows pods

scripts/k8s_unit_windows.ps1
=> skipping linux-speicifc proxy packages during windows unit test execution

.github/workflows/capz.yml, .github/workflows/hyperv-webhook-build.yaml
Fixes warnings in CI and updates to latest versions
=> Update gh actions to latest versions

capz/run-capz-e2e.sh
In https://github.com/kubernetes-sigs/windows-testing/pull/430/files I bumped the default to 2019 and this is causing conflicts across tests https://github.com/kubernetes/kubernetes/issues/125187#issuecomment-2137858270
While we resolve the issue switching back to the default
=> Use 2019 as default

capz/run-capz-e2e.sh
we got a report that the test was failing https://github.com/kubernetes/kubernetes/issues/125240, but in reality we are just waint for the cluster to come up.  This will throw away the error while we are waiting.
=> don't repeat output

scripts/ci-k8s-unit-test.sh, scripts/k8s_unit_windows.ps1
We want to be able to run the unit tests only on a subset of packages, reducing the amount of total time spent by the job. For this, we need to be able to specify a list of packages to test.
Added ``testPackages`` argument to the ``k8s_unit_windows.ps1`` script.
``ci-k8s-unit-test.sh`` can be configured with the ``TEST_PACKAGES`` env variable, which will then pass to the ``k8s_unit_windows.ps1`` script if given.
=> Parameterize k8s_unit_windows.ps1 to accept a list of packages

capz/templates/gmsa-ci.yaml, capz/templates/gmsa-pr.yaml, capz/templates/shared-image-gallery-ci.yaml, capz/templates/windows-base.yaml, capz/templates/windows-ci.yaml, capz/templates/windows-pr.yaml
This PR adds a new kubeadm action that sets some registries to instruct Windows to write dump for process crashes to c:\localdumps so they can be collected by our log collection scripts.
This was done in the capz templates (https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/aa536cccba7657c4f924e5c5ecc5fca9694c800f/templates/test/ci/cluster-template-prow.yaml#L304-L316) and I could have sworn it was done here to...
=> Set registry keys to write process dumps to c:\localdumps

scripts/k8s_unit_windows.ps1
The unittest ``cmdTestCmdConfigImagesList/valid:_latest_stable_Kubernetes_version_should_not_throw_the_warning_that_a_supported_etcd_version_cannot_be_found`` currently fails because the command ``kubeadm config images list --v=1 --kubernetes-version=stable-1`` outputs the warning ``"WARNING: could not find officially supported version of etcd for Kubernetes v1.27.15, falling back to the nearest etcd version (3.5.14-0)"``, and the test explicitly checks against this specific type of warning.
This seems to happen when the build flags used when building kubeadm are older than expected. Building with new flags solves this issue.
=> unittests: Updates kubeadm build flags

capz/run-capz-e2e.sh
In #433, we added a flag but it was already there and so it was overwritten by the second one.
/assign @claudiubelu
=> Add retries properly

capz/run-capz-e2e.sh
After #430, the template was hard coded instead of using the calculated value.  We also were not copying the file to the logs for debugging purposes.
=> Use calculated template and save it for debugging

capz/readme.md
As part of the removal of secrets, we need to remove the secrets to the storage accounts too.
This updates the docs with the details.
/hold
dependent on changes in capz https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4939
=> Remove storage secret from docs

capz/run-capz-e2e.sh
In #447, I didn't take into account that this script is used across various versions of CAPZ.  This adds a check if the token file is present then we will not parse the prow cred secret
=> Parse prow creds when token file not present

capz/run-capz-e2e.sh
https://github.com/kubernetes-sigs/windows-testing/pull/448 wasn't quiet right because we must do this before we "ensure azure cli" or we won't have the required envs
=> Must parse values before loading cli

.gitignore, capz/run-capz-e2e.sh
Building on this PR: https://github.com/kubernetes-sigs/windows-testing/pull/439/files to build ability to test job migration to Azure CNCF subscription.
=> Cncf job migration test

capz/run-capz-e2e.sh
The new sub is seeing issues with our windows sku in `westus3` this follows https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/5003
```
the requested VM size for resource 'Following SKUs have failed for Capacity Restrictions: Standard_DS2_v2' is currently not available in location 'WestUS3'.
```
=> Update regions for new sub

capz/run-capz-e2e.sh
skip  - `Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret` in community clusters until https://github.com/kubernetes-sigs/windows-testing/issues/446 is resolved
=> update skip until #446 is resolved

capz/run-capz-e2e.sh, capz/templates/gmsa-ci.yaml, capz/templates/gmsa-pr.yaml, capz/templates/shared-image-gallery-ci.yaml, capz/templates/windows-base.yaml, capz/templates/windows-ci.yaml, capz/templates/windows-pr.yaml, images/image-repo-list-private-registry-community
Wiring user identities to windows nodes
=> Wiring user identities

capz/run-capz-e2e.sh, capz/templates/gmsa-ci.yaml, capz/templates/gmsa-pr.yaml, capz/templates/shared-image-gallery-ci.yaml, capz/templates/windows-base.yaml, capz/templates/windows-ci.yaml, capz/templates/windows-pr.yaml, images/image-repo-list-private-registry-community
This reverts commit 8dc7bb1d147adc1875c8908edd6365d3ef929f37.
This is passing for ws2022 but started failing in ws2019 with `E0802 14:31:52.114636    6048 kuberuntime_manager.go:269] "Failed to register CRI auth plugins" err="plugin binary directory /var/lib/kubelet/credential-provider did not exist"`
also seeing some interesting errors in logs:
```
b1d0a36836c1","Type":"ContainerStarted","Data":"34516e609fce5ffa186d271994a9288502d1a52e440cb9ca51a309d5520b6eea"}
E0802 17:18:50.454190    4912 log.go:32] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"e2eprivatecommunity.azurecr.io/alpine:3.7\": failed to resolve reference \"e2eprivatecommunity.azurecr.io/alpine:3.7\": e2eprivatecommunity.azurecr.io/alpine:3.7: not found" …
```
=> Revert "Wiring user identities"

capz/readme.md, capz/templates/gmsa-ci.yaml, capz/templates/gmsa-pr.yaml, capz/templates/shared-image-gallery-ci.yaml, capz/templates/windows-base.yaml, capz/templates/windows-ci.yaml, capz/templates/windows-pr.yaml
This feature-gate was set to on-by-default in v1.27 (https://github.com/kubernetes/kubernetes/blob/release-1.27/pkg/features/kube_features.go#L1008) so we don't need to update anything else to have the feature turned on for all our test passes
/cc @ritikaguptams
=> Stop setting HPAContianerMetrics feature-gate because it will be removed in v1.32

capz/templates/gmsa-ci.yaml, capz/templates/gmsa-pr.yaml, capz/templates/shared-image-gallery-ci.yaml, capz/templates/windows-base.yaml, capz/templates/windows-ci.yaml, capz/templates/windows-pr.yaml
Admin Users require to have the public key added to c:/ProgramData/ssh/administrators_authorized_keys. [reference](https://learn.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#administrative-user)
=> copy ssh key to administrator authorized keys

scripts/prepare_env_windows.ps1
quick fix to get golang version matching what is used in k/k.
I'm going to look into parallelizing the execution of unit tests and will make this configurable as part of a later PR.
=> bump golang version to v1.23.6 for unit tests

scripts/ci-k8s-unit-test.sh, scripts/k8s_unit_windows.ps1, scripts/prepare_env_windows.ps1
Fixes #472 
This PR
- fixes and issue where some powershell environments may not have $HOME set (use $HOMEPATH as a fallback)
- Runs the unit tests for various go packages in parallel
- Fixes and issue where failing unit tests do not cause the PROW job to fail
=> Unit tests fixes and parallel

capz/run-capz-e2e.sh, capz/templates/gmsa-ci.yaml, capz/templates/gmsa-pr.yaml, capz/templates/shared-image-gallery-ci.yaml, capz/templates/windows-base.yaml, capz/templates/windows-ci.yaml, capz/templates/windows-pr.yaml, images/image-repo-list-private-registry-community
This is on top of PR https://github.com/kubernetes-sigs/windows-testing/pull/460 and trying to address: https://github.com/kubernetes-sigs/windows-testing/pull/465. it looks to me that the test failure is more like the pre-created MI does not match the cluster region, instead of windows SKU related. I have tested with my private registry with this change, and it works fine for both 2019 and 2022
=> Enable the cluster worker node ManageIdentity

capz/run-capz-e2e.sh
this e2e test will need special kubelet config, plan is to move to the e2e node test
=> Temp disable the graceful shutdown e2e test case

capz/run-capz-e2e.sh
This will skip any alpha tests for serial slow jobs such as:
[Feature:SchedulerAsyncPreemption] [FeatureGate:SchedulerAsyncPreemption] [Alpha]
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-e2e-capz-master-windows-serial-slow/1891895226952323072
=> skip alpha tests by default for serial slow

capz/run-capz-e2e.sh, capz/templates/1.29/windows-ci.yaml
the 1.29 jobs started failing after https://github.com/kubernetes-sigs/windows-testing/pull/481
The 1.29 is technically [end of life](https://kubernetes.io/releases/patch-releases/#non-active-branch-history) but there might be one more release coming. 
I tried to figure out why the credential provider wasn't installing properly but couldn't figure it out. Since it is EOL, I don't think its really worth spending a ton of time on this.
This copies the pr/ci templates from the commit prior to #481 at https://github.com/kubernetes-sigs/windows-testing/tree/c753db04764b1aece57dd2108a9d01a7c15ad030/capz/templates
https://kubernetes.slack.com/archives/C0SJ4AFB7/p1740515268283749
/sig windows
/assign @marosset @zylxjtu
=> Use older template for running 1.29 jobs

capz/run-capz-e2e.sh, capz/templates/1.29/windows-ci.yaml, capz/templates/1.29/windows-pr.yaml
follow up to https://github.com/kubernetes-sigs/windows-testing/pull/486
in #481 the user identity string also changed, this fixes the template to use that value and adds the pr template from https://github.com/kubernetes-sigs/windows-testing/tree/c753db04764b1aece57dd2108a9d01a7c15ad030/capz/templates.  It also cleans up an extra `/`
/assign @marosset @zylxjtu @iankingori
=> Use correct user identity

capz/run-capz-e2e.sh
Skip some tests for beta features that are off-by-default 
https://testgrid.k8s.io/sig-windows-master-release#capz-windows-master
specifically:
- [It] [sig-api-machinery] ResourceQuota [FeatureGate:VolumeAttributesClass] [Beta] [Feature:OffByDefault] should verify ResourceQuota's volume attributes class scope (quota set to pvc count: 1) against 2 pvcs with same volume attributes class.
- Kubernetes e2e suite.[It] [sig-api-machinery] ResourceQuota [FeatureGate:VolumeAttributesClass] [Beta] [Feature:OffByDefault] should verify ResourceQuota's volume attributes class scope (quota set to pvc count: 1) against a pvc with different volume attributes class.
These need feature gates set in
- api-server
- controller-manager
- csi drivers
https://github.com/kubernetes/enhancements/blob/1d9ad49058f01 …
=> Skip some beta tests for off-by-default features

scripts/ci-k8s-common.sh, scripts/ci-k8s-e2e-node-test.sh, scripts/ci-k8s-unit-test.sh, scripts/k8s_e2e_node_windows.ps1, scripts/prepare_e2e_node_windows.ps1
Objective:
To make scripts ready for adding prow job of windows e2e node test.
Refactor the bash file, so that most of the common part can be used by both unit test and windows e2e node test.
Local run (from a linux machine) passed for both unit test and e2e node test
The running of this prow job will have dependency on adding the windows e2e node test in k8s repo
=> Add prow job scripts for windows node e2e test

capz/run-capz-e2e.sh, capz/templates/calico/values.yaml
Calico isn't actively tested for 3.26.x. Bumping it to 3.28 gives reasonable coverage of currently supported Kubernetes versions.
From CAPZ Slack, it does not look like there is any limitation on the version that can be used with CAPZ - https://kubernetes.slack.com/archives/CEX9HENG7/p1697054837360589?thread_ts=1697048137.410809&channel=CEX9HENG7&message_ts=1697054837.360589
Therefore, I propose we bump CALICO_VERSION to 3.28.x, as it's an actively maintained version.
=> Bump Calico version to 3.29

scripts/ci-k8s-common.sh, scripts/ci-k8s-unit-test.sh, scripts/k8s_unit_windows.ps1
Fixing hangs in windows unit test jobs by doing a couple of things,
- Running each gotestsum.exe instance with cmd.exe and logging to a file - Occasionally powershell jobs are hanging because the input buffers are filling up and doing realtime reads from without powershell jobs is unreliable
- Limiting parallelism in job (both by setting GOMAXPROC env and also only running up to 4 instances of gotestsum.exe at the same time.
- updating ssh connection timeout options to be more resiliant
This doesn't look like it is slowing down the overall job duration at all
=> Fixing hangs in windows unit test jobs
